### ISSUE TITLE
[Bug][python] Excessive allocation of `tiledb.Ctx` objects causes resource starvation & fatal error

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#1169]
## Summary

Opening a SOMA Collection in `tiledbsoma` creates a new `tiledb.Ctx` object, which in turn creates a threadpool. In some common and acceptable SOMA code patterns (e.g.,, using `Collection.__getitem__` to access a sub-collection), the implementation will generate a very large number of unreferenced (not garbage collected) `tiledb.Ctx` objects, which can lead to memory map resource starvation errors on Linux (due to the Linux kernel limit on mapped segments), which in turn leads to a failure to allocate a thread pool.

Work-around: embed `gc.collect()` calls directly in end-user code, in any location where there are a large number of Collection opens. In my opinion, this work-around should not be necessary -- it would be much better if the temporary `Ctx` objects were not created in the first place, as they serve no purpose other than to pass a timestamp in the `tiledb.Group` open.

Test case and analysis below. The test case is somewhat contrived to make the occasional error happen quickly (by tweaking the GC thresholds).

## Versions
```
tiledbsoma.__version__        1.1.1
TileDB-Py tiledb.version()    (0, 21, 1)
TileDB core version           2.15.0
libtiledbsoma version()       libtiledbsoma=;libtiledb=2.15.0
python version                3.9.16.final.0
```
Note: also fails on tiledbsoma==1.0.0.  The core issue has been present since the timestamp support was introduced, pre-1.0.0.

System: Ubuntu 20.04.6 LTS
Kernel vm.max_map_count = 65530

## Additional Detail

I have Census-related scripts (using tiledbsoma) that periodically fail with:

> tiledb.cc.TileDBError: [TileDB::C++API] Error: Failed to create context

Or more rarely, they fail with an unexplained SEGV which is likely related. These failures occur without memory pressure or other obvious system issues. The error occurred much more frequently on Linux EC2 instances with very high core counts (eg., r6id.32xlarge), and more rarely on smaller boxes.

Setting `"config.logging_level": "5"` in the TileDB context produced a more nuanced error:

> [2023-03-25 17:11:31.045] [Process: 896131] [error] [1679764279772244317-Global] C API: TileDB Internal, std::exception; Error initializing thread pool of concurrency level 0; Resource temporarily unavailable

Digging into this more, I was able to determine that the cause of the above error was a failure to allocate a memory segment for the thread stack (done via strace) when the kernel VM `max_map_count` was exceeded for the process. This was confirmed with the test script, which showed that failure occured when there were in excess of 31105 threads and 63789 maps (kernel limit defaults to 65530).  I was also able to increase/decrease failure rate by tuning the kernel `max_map_count` (eg., `sysctl -w vm.max_map_count=32765` makes the error much more frequent).

As the test script (below) shows, the code simply opens and access a SOMA collection repeatedly. The root issue appears to be:
* any `Collection.open` (including `Collection.__getitem__` of another child collection) will create a _new_ `tiledb.Ctx`.  See code in `_tiledb_handles.py:GroupWrapper.open()` which creates a new `Ctx` object simply to set the timestamp.
* this behavior in turn creates a very large number of unused/unreferenced `Ctx` objets which are not (yet) garbage collected, each of which has a full thread pool
* On a large-core-count box, this will generate an excess of threads in between GC invocations

Which will lead to starvation of available memory maps.

Put another way, code such as:  `collection['foo']` will create a new `Ctx` and threadpool, which will then remain until the Python garbage collector runs. This occurs even when the user attempts to provide a `context` at the top-level SOMA call.

## Analysis/Comments

Superficially, the issue is the need for `tiledbsoma` to create a `Ctx` in each Collection/Group open, rather than re-using the existing Ctx objects.  This is exacerbated by TileDB-Py lacking a method to open a Group at a given timestamp, _without_ creating a new `tiledb.Ctx` (and its attendant resources). 

The TileDB Array classes support a `timestamp` param on the `open()` methods, so this concern is unique to Groups. The Groups API has an entirely different pattern which _only_ accepts timestmp ranges via the `Ctx` object. This, plus the SOMA-esque `__getitem__` (reification) pattern generates a lot of `Ctx` allocations.

## Test Case

A sample run of this test follows this section.

```
import gc
import re
import sys
import tiledb
import tiledbsoma


DEFAULT_TILEDB_CONFIG = {
    # Not required for demo
    "config.logging_level": "5",
    #
    # These are set to match the concurency levels on the machine I first
    # observed the failure. Having a moderately high number just accelerates
    # the failure.
    "sm.compute_concurrency_level": 128,
    "sm.io_concurrency_level": 128,
    "vfs.file.max_parallel_ops": 128,
    "vfs.s3.max_parallel_ops": 128,
    "vfs.s3.region": "us-west-2",
}


def get_thread_count() -> int:
    """Return the thread count for the current process. Retain the historical maximum."""
    with open("/proc/self/status") as f:
        status = f.read()
        thread_count = int(re.split(".*\nThreads:\t(\d+)\n.*", status)[1])
        get_thread_count.thread_count_high_water = max(
            thread_count, get_thread_count.thread_count_high_water
        )
    return thread_count


def get_map_count() -> int:
    """Return the memory map count for the current process. Retain the historical maximum."""
    with open("/proc/self/maps") as f:
        maps = f.read()
        map_count = maps.count("\n")
        get_map_count.map_count_high_water = max(
            map_count, get_map_count.map_count_high_water
        )
    return map_count


# historical maxima
get_thread_count.thread_count_high_water = -1
get_map_count.map_count_high_water = -1


def print_process_status(preface: str):
    """Print current and historical max of thread and (memory) map counts"""
    print(
        f"{preface} threads: {get_thread_count()} "
        f"[max: {get_thread_count.thread_count_high_water}], "
        f"maps: {get_map_count()} "
        f"[max: {get_map_count.map_count_high_water}]"
    )


TILEDB_CTX = tiledb.Ctx(DEFAULT_TILEDB_CONFIG)
SOMA_TILEDB_CONTEXT = tiledbsoma.options.SOMATileDBContext(
    tiledb_ctx=TILEDB_CTX, timestamp=None
)


def main():
    # this just prints out GC stats when it runs
    gc.set_debug(gc.DEBUG_STATS)

    # this slows down GC a bit, to help accelerate the demonstration
    gc.set_threshold(*[4 * i for i in gc.get_threshold()])

    soma_path = "s3://cellxgene-data-public/cell-census/2023-03-16/soma/"
    counter = 0
    while True:
        print_process_status(f"[A:{counter}]")
        with tiledbsoma.Collection.open(
            soma_path, context=SOMA_TILEDB_CONTEXT
        ) as census:
            print(census["census_data"]["homo_sapiens"].ms["RNA"].X["raw"])

        # Uncommenting this line will prevent the issue from occuring
        # gc.collect()

        print_process_status(f"[B:{counter}]")
        counter = counter + 1


if __name__ == "__main__":
    sys.exit(main())
```

## Sample Run of the Test Case

```
$ python tmp/ctx_test.py 
[A:0] threads: 385 [max: 385], maps: 1813 [max: 1813]
<SparseNDArray 's3://cellxgene-data-public/cell-census/2023-03-16/soma/census_data/homo_sapiens/ms/RNA/X/raw' (open for 'r')>
[B:0] threads: 1921 [max: 1921], maps: 4962 [max: 4962]
[A:1] threads: 1921 [max: 1921], maps: 4962 [max: 4962]
<SparseNDArray 's3://cellxgene-data-public/cell-census/2023-03-16/soma/census_data/homo_sapiens/ms/RNA/X/raw' (open for 'r')>
[B:1] threads: 3457 [max: 3457], maps: 8074 [max: 8074]
[A:2] threads: 3457 [max: 3457], maps: 8074 [max: 8074]
<SparseNDArray 's3://cellxgene-data-public/cell-census/2023-03-16/soma/census_data/homo_sapiens/ms/RNA/X/raw' (open for 'r')>
[B:2] threads: 4993 [max: 4993], maps: 11202 [max: 11202]
[A:3] threads: 4993 [max: 4993], maps: 11202 [max: 11202]
<SparseNDArray 's3://cellxgene-data-public/cell-census/2023-03-16/soma/census_data/homo_sapiens/ms/RNA/X/raw' (open for 'r')>
[B:3] threads: 6529 [max: 6529], maps: 14324 [max: 14324]
[A:4] threads: 6529 [max: 6529], maps: 14324 [max: 14324]
<SparseNDArray 's3://cellxgene-data-public/cell-census/2023-03-16/soma/census_data/homo_sapiens/ms/RNA/X/raw' (open for 'r')>
[B:4] threads: 8065 [max: 8065], maps: 17450 [max: 17450]
[A:5] threads: 8065 [max: 8065], maps: 17450 [max: 17450]
<SparseNDArray 's3://cellxgene-data-public/cell-census/2023-03-16/soma/census_data/homo_sapiens/ms/RNA/X/raw' (open for 'r')>
[B:5] threads: 9601 [max: 9601], maps: 20572 [max: 20572]
[A:6] threads: 9601 [max: 9601], maps: 20572 [max: 20572]
<SparseNDArray 's3://cellxgene-data-public/cell-census/2023-03-16/soma/census_data/homo_sapiens/ms/RNA/X/raw' (open for 'r')>
[B:6] threads: 11137 [max: 11137], maps: 23696 [max: 23696]
[A:7] threads: 11137 [max: 11137], maps: 23696 [max: 23696]
<SparseNDArray 's3://cellxgene-data-public/cell-census/2023-03-16/soma/census_data/homo_sapiens/ms/RNA/X/raw' (open for 'r')>
[B:7] threads: 12673 [max: 12673], maps: 26822 [max: 26822]
[A:8] threads: 12673 [max: 12673], maps: 26822 [max: 26822]
<SparseNDArray 's3://cellxgene-data-public/cell-census/2023-03-16/soma/census_data/homo_sapiens/ms/RNA/X/raw' (open for 'r')>
[B:8] threads: 14209 [max: 14209], maps: 29944 [max: 29944]
[A:9] threads: 14209 [max: 14209], maps: 29944 [max: 29944]
<SparseNDArray 's3://cellxgene-data-public/cell-census/2023-03-16/soma/census_data/homo_sapiens/ms/RNA/X/raw' (open for 'r')>
[B:9] threads: 15745 [max: 15745], maps: 33058 [max: 33058]
[A:10] threads: 15745 [max: 15745], maps: 33058 [max: 33058]
<SparseNDArray 's3://cellxgene-data-public/cell-census/2023-03-16/soma/census_data/homo_sapiens/ms/RNA/X/raw' (open for 'r')>
[B:10] threads: 17281 [max: 17281], maps: 36136 [max: 36136]
[A:11] threads: 17281 [max: 17281], maps: 36136 [max: 36136]
<SparseNDArray 's3://cellxgene-data-public/cell-census/2023-03-16/soma/census_data/homo_sapiens/ms/RNA/X/raw' (open for 'r')>
[B:11] threads: 18817 [max: 18817], maps: 39209 [max: 39209]
[A:12] threads: 18817 [max: 18817], maps: 39209 [max: 39209]
<SparseNDArray 's3://cellxgene-data-public/cell-census/2023-03-16/soma/census_data/homo_sapiens/ms/RNA/X/raw' (open for 'r')>
[B:12] threads: 20353 [max: 20353], maps: 42281 [max: 42281]
[A:13] threads: 20353 [max: 20353], maps: 42281 [max: 42281]
<SparseNDArray 's3://cellxgene-data-public/cell-census/2023-03-16/soma/census_data/homo_sapiens/ms/RNA/X/raw' (open for 'r')>
[B:13] threads: 21889 [max: 21889], maps: 45353 [max: 45353]
[A:14] threads: 21889 [max: 21889], maps: 45353 [max: 45353]
<SparseNDArray 's3://cellxgene-data-public/cell-census/2023-03-16/soma/census_data/homo_sapiens/ms/RNA/X/raw' (open for 'r')>
[B:14] threads: 23425 [max: 23425], maps: 48425 [max: 48425]
[A:15] threads: 23425 [max: 23425], maps: 48425 [max: 48425]
<SparseNDArray 's3://cellxgene-data-public/cell-census/2023-03-16/soma/census_data/homo_sapiens/ms/RNA/X/raw' (open for 'r')>
[B:15] threads: 24961 [max: 24961], maps: 51497 [max: 51497]
[A:16] threads: 24961 [max: 24961], maps: 51497 [max: 51497]
<SparseNDArray 's3://cellxgene-data-public/cell-census/2023-03-16/soma/census_data/homo_sapiens/ms/RNA/X/raw' (open for 'r')>
[B:16] threads: 26497 [max: 26497], maps: 54569 [max: 54569]
[A:17] threads: 26497 [max: 26497], maps: 54569 [max: 54569]
<SparseNDArray 's3://cellxgene-data-public/cell-census/2023-03-16/soma/census_data/homo_sapiens/ms/RNA/X/raw' (open for 'r')>
[B:17] threads: 28033 [max: 28033], maps: 57641 [max: 57641]
[A:18] threads: 28033 [max: 28033], maps: 57641 [max: 57641]
<SparseNDArray 's3://cellxgene-data-public/cell-census/2023-03-16/soma/census_data/homo_sapiens/ms/RNA/X/raw' (open for 'r')>
[B:18] threads: 29569 [max: 29569], maps: 60713 [max: 60713]
[A:19] threads: 29569 [max: 29569], maps: 60713 [max: 60713]
<SparseNDArray 's3://cellxgene-data-public/cell-census/2023-03-16/soma/census_data/homo_sapiens/ms/RNA/X/raw' (open for 'r')>
[B:19] threads: 31105 [max: 31105], maps: 63785 [max: 63785]
[A:20] threads: 31105 [max: 31105], maps: 63785 [max: 63785]
[2023-03-25 19:32:57.264] [Process: 979393] [error] [1679772765198059369-Global] C API: TileDB Internal, std::exception; Error initializing thread pool of concurrency level 0; Resource temporarily unavailable
Traceback (most recent call last):
  File "/home/bruce/cell-census/tmp/ctx_test.py", line 90, in <module>
    sys.exit(main())
  File "/home/bruce/cell-census/tmp/ctx_test.py", line 80, in main
    print(census["census_data"]["homo_sapiens"].ms["RNA"].X["raw"])
  File "/home/bruce/cell-census/venv/lib/python3.9/site-packages/somacore/_mixin.py", line 71, in __get__
    return inst[self.item_name]
  File "/home/bruce/cell-census/venv/lib/python3.9/site-packages/tiledbsoma/_collection.py", line 421, in __getitem__
    entry.soma = _factory._open_internal(
  File "/home/bruce/cell-census/venv/lib/python3.9/site-packages/tiledbsoma/_factory.py", line 142, in _open_internal
    handle = opener(uri, mode, context, timestamp)
  File "/home/bruce/cell-census/venv/lib/python3.9/site-packages/tiledbsoma/_tdb_handles.py", line 85, in open
    tdb = cls._opener(uri, mode, context, timestamp_ms)
  File "/home/bruce/cell-census/venv/lib/python3.9/site-packages/tiledbsoma/_tdb_handles.py", line 224, in _opener
    uri, mode, ctx=_group_timestamp_ctx(context.tiledb_ctx, timestamp)
  File "/home/bruce/cell-census/venv/lib/python3.9/site-packages/tiledbsoma/_tdb_handles.py", line 238, in _group_timestamp_ctx
    return tiledb.Ctx(group_cfg)
  File "/home/bruce/cell-census/venv/lib/python3.9/site-packages/tiledb/ctx.py", line 344, in __init__
    super().__init__(_config)
tiledb.cc.TileDBError: [TileDB::C++API] Error: Failed to create context
gc: collecting generation 2...
gc: objects in each generation: 1716 2525 118640
gc: objects in permanent generation: 0
[2023-03-25 19:32:57.295] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:32:57.623] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:32:57.942] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:32:58.257] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:32:58.573] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:32:58.887] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:32:59.210] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:32:59.518] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:32:59.820] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:00.130] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:00.451] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:00.755] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:01.052] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:01.347] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:01.654] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:01.945] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:02.230] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:02.520] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:02.809] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:03.080] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:03.353] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:03.618] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:03.885] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:04.164] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:04.422] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:04.677] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:04.930] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:05.185] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:05.424] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:05.663] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:05.900] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:06.139] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:06.368] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:06.594] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:06.819] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:07.038] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:07.256] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:07.469] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:07.681] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:07.892] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:08.112] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:08.316] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:08.514] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:08.713] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:08.903] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:09.096] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:09.281] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:09.466] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:09.652] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:09.835] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:10.015] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:10.193] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:10.361] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:10.522] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:10.686] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:10.845] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:10.998] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:11.152] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:11.305] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:11.450] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:11.598] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:11.744] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:11.885] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:12.027] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:12.173] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:12.301] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:12.430] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:12.560] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:12.689] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:12.811] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:12.928] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:13.045] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:13.154] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:13.260] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:13.364] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:13.468] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:13.571] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:13.672] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:13.763] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:13.850] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:13.939] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:14.027] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:14.105] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:14.185] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:14.258] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:14.328] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:14.398] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:14.462] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:14.523] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:14.587] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:14.648] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:14.707] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:14.763] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:14.811] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:14.855] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:14.902] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:14.948] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:14.990] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:15.025] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:15.062] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:15.094] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:15.125] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:15.152] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:15.180] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:15.206] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:15.231] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:15.253] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:15.274] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:15.294] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:15.313] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:15.331] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:15.348] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:15.365] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:15.380] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:15.394] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:15.408] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:15.421] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:15.433] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:15.445] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:15.456] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
gc: done, 1492 unreachable, 0 uncollectable, 18.1942s elapsed
gc: collecting generation 2...
gc: objects in each generation: 2393 0 119451
gc: objects in permanent generation: 0
[2023-03-25 19:33:15.498] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:15.507] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
[2023-03-25 19:33:15.516] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
gc: done, 265 unreachable, 0 uncollectable, 0.0506s elapsed
gc: collecting generation 2...
gc: objects in each generation: 0 0 100668
gc: objects in permanent generation: 0
[2023-03-25 19:33:15.564] [Process: 979393] [trace] [1679772765198059369-Global] malloc_trim did unmap memory
gc: done, 51022 unreachable, 0 uncollectable, 0.0422s elapsed
```

**Comment by johnkerl** [comment]
#1715 is merged
