### ISSUE TITLE
[r] Audit TileDBSOMA-R against the object-lifecycle specification

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#1241]
## Overview

We have open and create methods, and read and write modes, syntactically.

We need to audit the UX of TileDBSOMA-R to verify it matches the [object-lifecycle part of the spec](https://github.com/single-cell-data/SOMA/blob/main/abstract_specification.md#object-lifecycle) semantically.

Some things we can check (ideally, all via existing or new unit-test cases) -- see partial checklist below

We can split out several implementation issues for this.

* #1346
* #1347 

## Checklist as of 2023-05-02:

* [ ] (1346) `mode()` accessor exists
  * [ ] (1346) Returns `"READ"` after array/group opened for read
  * [ ] (1346) Returns `"WRITE"` after array/group opened for write, and after calling `create`
  * [ ] (1346) Returns `"CLOSED"` after array/group is closed
* [ ] (1346) For each object type: if opened for reading: `write` raises an error
* For each object type: if opened for writing:
  * [ ] (1346) `read()` raises an error
  * [ ] (1346) for all types: metadata can be inspected
  * [ ] (1346) for arrays: schema, and data derived from the schema, can be inspected
  * [ ] (1346) for collections: members of the collection are accessible
* After `close`:
  * [ ] (1346) `read` raises an error
  * [ ] (1346) `write` raises an error
* [ ] (1346) The `open` methods return an object opened for read (default, or `mode="r"`) or write (`mode="w"`)
* [ ] (1346) Whether mode is read or write, `open` raises an error if the object does not exist
* [ ] (1346) The `create` methods return an object opened in write mode
* [ ] Timestamps (1347):
  * Open at time T1
  * Some other processes writes at time T2
  * Original process opened at T1 does not see these changes until it closes and re-opens
* Of course the [object-lifecycle part of the spec](https://github.com/single-cell-data/SOMA/blob/main/abstract_specification.md#object-lifecycle) is the authoritative list
  * [ ] Check to see if we've missed anything else

## Examples

Some examples of what TileDB-SOMA-Py currently does, to illustrate some of the things we need to change in TileDB-SOMA-R:

### Require create before open; open fails on non-exist case

```
>>> tiledbsoma.Experiment.open('nonesuch')
Traceback (most recent call last):
...
tiledb.cc.TileDBError: [TileDB::GroupDirectory] Error: Cannot open group; Group does not exist.
...
tiledbsoma._exception.DoesNotExistError: 'nonesuch' does not exist
```

```
> SOMAExperimentOpen('nonesuch')
<SOMAExperiment>
  uri: nonesuch
```

### Open-mode is used and is queryable

```
>>> exp = tiledbsoma.Experiment.open('s/v/ileum')
>>> exp.mode
'r'

>>> exp = tiledbsoma.Experiment.open('s/v/ileum', 'w')
>>> exp.mode
'w'

>>> exp = tiledbsoma.Experiment.open('s/v/ileum', 'r')
>>> exp.mode
'r'
```

### Write fails when object is open for read

```
>>> exp = tiledbsoma.Experiment.open('ileum')
>>> pydict = {'soma_joinid':[]}
>>> arrow_df = pa.Table.from_pydict(pydict)
>>> exp.obs.write(arrow_df)
Traceback (most recent call last):
...
tiledbsoma._exception.SOMAError: cannot write to <ArrayWrapper r on 'file:///Users/johnkerl/s/v/ileum/obs'>; it is open for reading
```

### Read fails when object is open for write

Except as noted above: metadata are queryable, and group members are queryable:

```
>>> exp = tiledbsoma.Experiment.open('ileum', 'w')

>>> exp.ms
<Collection 'file:///Users/johnkerl/s/v/ileum/ms' (open for 'w') (2 items)
    'RNA': 'file:///Users/johnkerl/s/v/ileum/ms/RNA' (unopened)
    'raw': 'file:///Users/johnkerl/s/v/ileum/ms/raw' (unopened)>

>>> exp.ms["RNA"]
<Measurement 'file:///Users/johnkerl/s/v/ileum/ms/RNA' (open for 'w') (4 items)
    'obsm': 'file:///Users/johnkerl/s/v/ileum/ms/RNA/obsm' (unopened)
    'varm': 'file:///Users/johnkerl/s/v/ileum/ms/RNA/varm' (unopened)
    'var': 'file:///Users/johnkerl/s/v/ileum/ms/RNA/var' (unopened)
    'X': 'file:///Users/johnkerl/s/v/ileum/ms/RNA/X' (unopened)>

>>> exp.ms["RNA"].X
<Collection 'file:///Users/johnkerl/s/v/ileum/ms/RNA/X' (open for 'w') (1 item)
    'data': 'file:///Users/johnkerl/s/v/ileum/ms/RNA/X/data' (unopened)>

>>> exp.ms["RNA"].X["data"]
<SparseNDArray 'file:///Users/johnkerl/s/v/ileum/ms/RNA/X/data' (open for 'w')>

>>> exp.ms["RNA"].X["data"].read()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/johnkerl/git/single-cell-data/TileDB-SOMA/apis/python/src/tiledbsoma/_sparse_nd_array.py", line 143, in read
    self._check_open_read()
  File "/Users/johnkerl/git/single-cell-data/TileDB-SOMA/apis/python/src/tiledbsoma/_tiledb_object.py", line 284, in _check_open_read
    raise ValueError(f"{self} is open for writing, not reading")
ValueError: <SparseNDArray 'file:///Users/johnkerl/s/v/ileum/ms/RNA/X/data' (open for 'w')> is open for writing, not reading
```

**Comment by johnkerl** [comment]
As discussed in Friday's meeting #1325 is nearing completion and solves much of this.

@mlin and @eddelbuettel can perhaps work together on the timestamp bits which will solve the rest.

**Comment by johnkerl** [comment]
Closing this audit task now that #1346 and #1347 have been defined and assigned
