### ISSUE TITLE
[Bug] Consolidation Issues (Unsupported URI Scheme Error)

### ISSUE THREAD

**Issue by mdylan2** [single-cell-data/TileDB-SOMA#1251]
**Describe the bug**
Having an issue consolidating an array I created within a SOMA. Not sure how to reproduce but I'm using very barebones code here. 

I had consolidated a few other X arrays within the SOMA. My machine then timed out when it got to the `col_raw` array. So, I tried to consolidate this array by running some barebones `tiledb` code.

Running this on a r5.4xlarge instance (128GB memory) with a EBS volume attached. I cannot consolidate the obs, or other X arrays now either.

Is there anything that I'm missing here?

**To Reproduce**
```
import tiledb

if __name__ == "__main__":


    uri = "/home/ubuntu/human_data/ms/RNA/X/col_raw"

    ctx = tiledb.Ctx({
        "sm.mem.total_budget": 50*1024**3,
        "sm.consolidation.max_step_frags": 50, 
        "sm.consolidation.min_step_frags": 3,})
    tiledb.consolidate(uri, ctx = ctx)
```

Error:
```Traceback (most recent call last):
  File "/home/ubuntu/consolidate.py", line 14, in <module>
    tiledb.consolidate(uri, ctx = ctx)
  File "tiledb/libtiledb.pyx", line 3061, in tiledb.libtiledb.consolidate
  File "tiledb/libtiledb.pyx", line 3148, in tiledb.libtiledb._consolidate_timestamp
  File "tiledb/libtiledb.pyx", line 368, in tiledb.libtiledb._raise_ctx_err
  File "tiledb/libtiledb.pyx", line 353, in tiledb.libtiledb._raise_tiledb_error
tiledb.cc.TileDBError: [TileDB::VFS] Error: Unsupported URI scheme:
```

**Versions (please complete the following information):**
tiledbsoma.__version__        1.2.1
TileDB-Py tiledb.version()    (0, 21, 2)
TileDB core version           2.15.1
libtiledbsoma version()       libtiledbsoma=;libtiledb=2.15.0
python version                3.10.6.final.0
OS version                    Linux 5.15.0-1031-aws

**Comment by johnkerl** [comment]
@mdylan2 everywhere in TileDB Embedded that prints `Unsupported URI scheme:` follows that immediately with a print of the URI. Which here is appearing as the empty string (odd), unless you are missing a line of output.

Can you check to be sure there's no URI after `Error: Unsupported URI scheme:`?

**Comment by mdylan2** [comment]
I double checked and I don't have a print of the URI. 

If I run it without the `sm.mem.total_budget` parameter, it gives me this error instead:
```
File "/home/ubuntu/consolidate.py", line 9, in <module>
    tiledb.consolidate(uri, ctx = ctx)
  File "tiledb/libtiledb.pyx", line 3061, in tiledb.libtiledb.consolidate
  File "tiledb/libtiledb.pyx", line 3148, in tiledb.libtiledb._consolidate_timestamp
  File "tiledb/libtiledb.pyx", line 368, in tiledb.libtiledb._raise_ctx_err
  File "tiledb/libtiledb.pyx", line 353, in tiledb.libtiledb._raise_tiledb_error
tiledb.cc.TileDBError: [TileDB::SparseGlobalOrderReaderError] Error: Cannot load a single tile for fragment, increase memory budget, tile size : 1983568, per fragment memory 1356419.686710, total budget 10737418240 , num fragments to process 3958
```

**Comment by johnkerl** [comment]
@mdylan2 thanks!

Can you show me the output of

```
with tiledb.open("/home/ubuntu/human_data/ms/RNA/X/col_raw") as A:
    print(A.schema)
```
?

**Comment by johnkerl** [comment]
Another question: re

> My machine then timed out when it got to the col_raw array.

Did it time out on a previous consolidate, or on ingest?

Also, can you consolidate any of the other X layers?

**Comment by mdylan2** [comment]
```
ArraySchema(
  domain=Domain(*[
    Dim(name='soma_dim_0', domain=(0, 14156013), tile=2048, dtype='int64', filters=FilterList([ZstdFilter(level=3), ])),
    Dim(name='soma_dim_1', domain=(0, 122579), tile=2048, dtype='int64', filters=FilterList([ZstdFilter(level=3), ])),
  ]),
  attrs=[
    Attr(name='soma_data', dtype='float32', var=False, nullable=False, filters=FilterList([ByteShuffleFilter(), ZstdFilter(level=5), ])),
  ],
  cell_order='col-major',
  tile_order='col-major',
  capacity=131072,
  sparse=True,
  allows_duplicates=False,
)
```

the layers with row-major, row-major consolidated. I cannot consolidate the obs either.

**Comment by johnkerl** [comment]
@mdylan2 in addition to
```
"sm.mem.total_budget":50*1024**3
```
can we add
```
"py.init_buffer_bytes": 25_000_000_000
```
?

If this helps, great! If not I'll need to loop in @KiterLuc.

**Comment by mdylan2** [comment]
Still not working. Maybe I'll try and recreate the array.

**Comment by johnkerl** [comment]
Hi @mdylan2 --

* Can you share some information on how this SOMA experiment was created?
* Has there been any schema evolution?
* Have there been any deletes done on the data?
* Has there been any remove-and-replace of files within the storage?
* Would it be possible for you to share the data with us?
* Can you rerun the consolidate with `"config.logging_level": 5` in the config, and share the resulting output?

**Comment by mdylan2** [comment]
I can't share the data unfortunately. I did not remove/replace files in storage. 

Think I figured out the issue (error below). It's because I did not give it permissions to write to the storage volume. 

The consolidation worked for the row-oriented matrices because they were being run on an instance where write permissions were enabled for the storage volume. When the script timed out, I switched to run my barebones script above on another machine, which did not have permissions to write to the storage volume. 

Sorry for wasting your time here.

```[2023-04-14 10:51:41.295] [Process: 7026] [debug] [1681469494250081941-Context: 1] [Query: 1] [SparseGlobalOrderReader: 1] Initial data loaded
[2023-04-14 10:51:43.245] [Process: 7026] [debug] [1681469494250081941-Context: 1] [Query: 1] [SparseGlobalOrderReader: 1] Done adding result tiles, num result tiles 4040
[2023-04-14 10:51:43.245] [Process: 7026] [debug] [1681469494250081941-Context: 1] [Query: 1] [SparseGlobalOrderReader: 1] All result tiles loaded
[2023-04-14 10:51:43.413] [Process: 7026] [debug] [1681469494250081941-Context: 1] [Query: 1] [SparseGlobalOrderReader: 1] Done reading and unfiltering coords tiles
[2023-04-14 10:51:43.413] [Process: 7026] [debug] [1681469494250081941-Context: 1] [Query: 1] [SparseGlobalOrderReader: 1] Done applying query condition
[2023-04-14 10:51:43.422] [Process: 7026] [debug] [1681469494250081941-Context: 1] [Query: 1] [SparseGlobalOrderReader: 1] Done merging result cell slabs, num slabs 1353, buffers full true
[2023-04-14 10:51:45.858] [Process: 7026] [debug] [1681469494250081941-Context: 1] [Query: 1] [SparseGlobalOrderReader: 1] Done copying tiles, buffers full true
[2023-04-14 10:51:45.860] [Process: 7026] [debug] [1681469494250081941-Context: 1] [Query: 1] [SparseGlobalOrderReader: 1] Done with iteration, num result tiles 3293
[2023-04-14 10:51:45.943] [Process: 7026] [error] [1681469494645818293-Global] [TileDB::IO] Error: Cannot create directory '/home/ubuntu/data/corpus/04-12-2023_20:37:27/corpus_data/human_v6/obs/__fragments/__1681332003015_1681332003015_4520db34bd31472cac58eb0cf5262de0_18'; Permission denied
[2023-04-14 10:51:45.943] [Process: 7026] [error] [1681469494645818293-Global] [TileDB::VFS] Error: Unsupported URI scheme: 
[2023-04-14 10:51:46.039] [Process: 7026] [error] [1681469494645818293-Global] [TileDB::VFS] Error: Unsupported URI scheme: 
Traceback (most recent call last):
  File "/home/ubuntu/sctx_backend/consolidate.py", line 17, in <module>
    tiledb.consolidate(uri, ctx=ctx)
  File "tiledb/libtiledb.pyx", line 3061, in tiledb.libtiledb.consolidate
  File "tiledb/libtiledb.pyx", line 3148, in tiledb.libtiledb._consolidate_timestamp
  File "tiledb/libtiledb.pyx", line 368, in tiledb.libtiledb._raise_ctx_err
  File "tiledb/libtiledb.pyx", line 353, in tiledb.libtiledb._raise_tiledb_error
tiledb.cc.TileDBError: [TileDB::VFS] Error: Unsupported URI scheme: 
[2023-04-14 10:51:46.149] [Process: 7026] [trace] [1681469494645818293-Global] malloc_trim did unmap memory
```

**Comment by johnkerl** [comment]
Thanks @mdylan2 ! I've filed https://github.com/TileDB-Inc/TileDB/issues/4041 to help.
