### ISSUE TITLE
[Bug] python quickstart example unable to convert from `h5ad`

### ISSUE THREAD

**Issue by ktpolanski** [single-cell-data/TileDB-SOMA#1525]
**Describe the bug**
I attempted to follow the [Python quick start guide](https://github.com/single-cell-data/TileDB-SOMA/wiki/Python-quick-start) and was unable to convert the supplied `h5ad` file to a SOMA object.

```python3
>>> pbmc3k_uri = tiledbsoma.io.from_h5ad("./pbmc3k", input_path = "pbmc3k.h5ad", measurement_name = "RNA")
/home/jovyan/my-conda-envs/tiledbsoma/lib/python3.9/site-packages/anndata/compat/__init__.py:229: FutureWarning: Moving element from .uns['neighbors']['distances'] to .obsp['distances'].

This is where adjacency matrices should go now.
  warn(
/home/jovyan/my-conda-envs/tiledbsoma/lib/python3.9/site-packages/anndata/compat/__init__.py:229: FutureWarning: Moving element from .uns['neighbors']['connectivities'] to .obsp['connectivities'].

This is where adjacency matrices should go now.
  warn(
Traceback (most recent call last):
  File "/home/jovyan/my-conda-envs/tiledbsoma/lib/python3.9/site-packages/tiledbsoma/io/ingest.py", line 1320, in _ingest_uns_ndarray
    soma_arr = _factory.open(arr_uri, "w", soma_type=DenseNDArray)
  File "/home/jovyan/my-conda-envs/tiledbsoma/lib/python3.9/site-packages/tiledbsoma/_factory.py", line 114, in open
    obj = _open_internal(_tdb_handles.open, uri, mode, context, tiledb_timestamp)
  File "/home/jovyan/my-conda-envs/tiledbsoma/lib/python3.9/site-packages/tiledbsoma/_factory.py", line 143, in _open_internal
    handle = opener(uri, mode, context, timestamp)
  File "/home/jovyan/my-conda-envs/tiledbsoma/lib/python3.9/site-packages/tiledbsoma/_tdb_handles.py", line 50, in open
    raise DoesNotExistError(f"{uri!r} does not exist")
tiledbsoma._exception.DoesNotExistError: 'pbmc3k/ms/RNA/uns/louvain_colors' does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jovyan/my-conda-envs/tiledbsoma/lib/python3.9/site-packages/tiledbsoma/io/ingest.py", line 140, in from_h5ad
    uri = from_anndata(
  File "/home/jovyan/my-conda-envs/tiledbsoma/lib/python3.9/site-packages/tiledbsoma/io/ingest.py", line 287, in from_anndata
    _maybe_ingest_uns(
  File "/home/jovyan/my-conda-envs/tiledbsoma/lib/python3.9/site-packages/tiledbsoma/io/ingest.py", line 1203, in _maybe_ingest_uns
    _ingest_uns_dict(
  File "/home/jovyan/my-conda-envs/tiledbsoma/lib/python3.9/site-packages/tiledbsoma/io/ingest.py", line 1276, in _ingest_uns_dict
    _ingest_uns_ndarray(
  File "/home/jovyan/my-conda-envs/tiledbsoma/lib/python3.9/site-packages/tiledbsoma/io/ingest.py", line 1322, in _ingest_uns_ndarray
    soma_arr = DenseNDArray.create(
  File "/home/jovyan/my-conda-envs/tiledbsoma/lib/python3.9/site-packages/tiledbsoma/_common_nd_array.py", line 93, in create
    schema = cls._build_tiledb_schema(
  File "/home/jovyan/my-conda-envs/tiledbsoma/lib/python3.9/site-packages/tiledbsoma/_common_nd_array.py", line 136, in _build_tiledb_schema
    raise TypeError(
TypeError: Unsupported type string -- SOMA NDArrays only support primtive Arrow types
```

The contents of `adata.uns['louvain_colors']`:
```python3
>>> adata.uns['louvain_colors']
array(['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b',
       '#e377c2', '#bcbd22'], dtype='<U7')
```

**To Reproduce**
```bash
conda create --name tiledbsoma python=3.9
conda activate tiledbsoma
pip install tiledbsoma
wget https://github.com/chanzuckerberg/cellxgene/raw/main/example-dataset/pbmc3k.h5ad
```

Then within python:
```python3
import tiledbsoma.io
pbmc3k_uri = tiledbsoma.io.from_h5ad("./pbmc3k", input_path = "pbmc3k.h5ad", measurement_name = "RNA")
```

Problem persists with `tiledbsoma` installed from conda rather than pip as well.

**Versions (please complete the following information):**
```python3
tiledbsoma.__version__        1.2.7
TileDB-Py tiledb.version()    (0, 21, 6)
TileDB core version           2.15.4
libtiledbsoma version()       libtiledb=2.15.2
python version                3.9.16.final.0
OS version                    Linux 4.15.0-112-generic
```

**Additional context**

**Comment by johnkerl** [comment]
Hi @ktpolanski and thanks for reporting this!

This was fixed in https://github.com/single-cell-data/TileDB-SOMA/pull/1514 and we have an upcoming release soon, and this bugfix will be included in that release.
