### ISSUE TITLE
[Bug] `tiledbsoma.io.from_h5ad` fails on h5ad with a grouped dataset with attribute named 'MeasurementID'

### ISSUE THREAD

**Issue by SSunkara** [single-cell-data/TileDB-SOMA#1799]
**Describe the bug**
Hello,
This is a novice attempt at converting our 'harmonized' h5ad (standardized nomenclature derived at our organization) to the TileDB data format. The code seems to work with the example provided in your dataset, but throws a ValueError with our version of the h5ad. 

**To Reproduce**

```
./TileDB-SOMA/apis/python/devtools/ingestor Cheng-GSE154763-esophagus-ESCA-scRNA-Homo_sapiens.Refseq.Grch38.h5ad
/Users/ssunka11/.Python3.11env/lib/python3.11/site-packages/tiledbsoma/io/conversions.py:58: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if isinstance(x, (np.ndarray, sp.spmatrix)) or not is_categorical_dtype(x):
Traceback (most recent call last):
  File "/Users/ssunka11/TileDB/./TileDB-SOMA/apis/python/devtools/ingestor", line 342, in <module>
    main()
  File "/Users/ssunka11/TileDB/./TileDB-SOMA/apis/python/devtools/ingestor", line 219, in main
    ingest_one(
  File "/Users/ssunka11/TileDB/./TileDB-SOMA/apis/python/devtools/ingestor", line 315, in ingest_one
    uri = tiledbsoma.io.from_h5ad(
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ssunka11/.Python3.11env/lib/python3.11/site-packages/tiledbsoma/io/ingest.py", line 170, in from_h5ad
    uri = from_anndata(
          ^^^^^^^^^^^^^
  File "/Users/ssunka11/.Python3.11env/lib/python3.11/site-packages/tiledbsoma/io/ingest.py", line 277, in from_anndata
    with _write_dataframe(
         ^^^^^^^^^^^^^^^^^
  File "/Users/ssunka11/.Python3.11env/lib/python3.11/site-packages/tiledbsoma/io/ingest.py", line 706, in _write_dataframe
    df.reset_index(inplace=True)
  File "/Users/ssunka11/.Python3.11env/lib/python3.11/site-packages/pandas/core/frame.py", line 6223, in reset_index
    new_obj.insert(
  File "/Users/ssunka11/.Python3.11env/lib/python3.11/site-packages/pandas/core/frame.py", line 4934, in insert
    raise ValueError(f"cannot insert {column}, already exists")
ValueError: cannot insert MeasurementID, already exists
```

**Versions (please complete the following information):**

```
tiledbsoma.__version__        1.4.3
TileDB-Py tiledb.version()    (0, 22, 3)
TileDB core version           2.16.3
libtiledbsoma version()       libtiledb=2.16.2
python version                3.11.4.final.0
OS version                    Darwin 22.6.0
```

**Additional context**

A partial dump of the h5ad structure showing the MeasurementID attribute:
```
h5dump -n Cheng-GSE154763-esophagus-ESCA-scRNA-Homo_sapiens.Refseq.Grch38.h5ad                                     
HDF5 "Cheng-GSE154763-esophagus-ESCA-scRNA-Homo_sapiens.Refseq.Grch38.h5ad" {
FILE_CONTENTS {
 group      /
 group      /X
 dataset    /X/data
 dataset    /X/indices
 dataset    /X/indptr
 group      /layers
 group      /obs
 group      /obs/Age
 dataset    /obs/Age/categories
 dataset    /obs/Age/codes
 group      /obs/AnatomicalEntity
 dataset    /obs/AnatomicalEntity/categories
 dataset    /obs/AnatomicalEntity/codes
 group      /obs/Author's cell type
 dataset    /obs/Author's cell type/categories
 dataset    /obs/Author's cell type/codes
 group      /obs/BarcodesCurated
 dataset    /obs/BarcodesCurated/categories
 dataset    /obs/BarcodesCurated/codes
 group      /obs/BroadAnatomicalEntity
 dataset    /obs/BroadAnatomicalEntity/categories
 dataset    /obs/BroadAnatomicalEntity/codes
 group      /obs/BroadCellType
 dataset    /obs/BroadCellType/categories
 dataset    /obs/BroadCellType/codes
 group      /obs/Cancer
 dataset    /obs/Cancer/categories
 dataset    /obs/Cancer/codes
 group      /obs/CellCount
 dataset    /obs/CellCount/categories
 dataset    /obs/CellCount/codes
 group      /obs/Condition
 dataset    /obs/Condition/categories
 dataset    /obs/Condition/codes
 group      /obs/Developmental stage
 dataset    /obs/Developmental stage/categories
 dataset    /obs/Developmental stage/codes
 group      /obs/ExperimentTag
 dataset    /obs/ExperimentTag/categories
 dataset    /obs/ExperimentTag/codes
 **group      /obs/Louvain clustering
 dataset    /obs/Louvain clustering/categories
 dataset    /obs/Louvain clustering/codes
 dataset    /obs/MeasurementID**
 group      /obs/Number of genes
 dataset    /obs/Number of genes/categories
 dataset    /obs/Number of genes/codes
```

**Comment by SSunkara** [comment]
@johnkerl - Thanks so much for the quick feedback. Turns out that there is an issue with our version of the h5ad. The MeasurementID column was duplicated (indexed and un-indexed columns).

I am going to close the issue. Really appreciate your help again.

**Comment by johnkerl** [comment]
Thanks @SSunkara !!
