### ISSUE TITLE
[Bug] Reading SOMA from s3 fails after aws datasync 

### ISSUE THREAD

**Issue by royassis** [single-cell-data/TileDB-SOMA#1824]
**Describe the bug**
We had encountered an interesting bug that I thought we can share and give a heads up about it. 
Reason for the bug and insights at "Additional context".

The following error occurs after copying files between s3 buckets using [AWS DataSync](https://aws.amazon.com/datasync/).
The error does not occur is copying files using `aws s3 cp`.

The error:
```python
>>> import tiledbsoma
>>> uri = "s3://reducted_bucket/reducet_dataset"
>>> exp = tiledbsoma.open(uri)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/general-env/lib/python3.10/site-packages/tiledbsoma/_factory.py", line 114, in open
    obj = _open_internal(_tdb_handles.open, uri, mode, context, tiledb_timestamp)
  File "/home/ubuntu/anaconda3/envs/general-env/lib/python3.10/site-packages/tiledbsoma/_factory.py", line 143, in _open_internal
    handle = opener(uri, mode, context, timestamp)
  File "/home/ubuntu/anaconda3/envs/general-env/lib/python3.10/site-packages/tiledbsoma/_tdb_handles.py", line 54, in open
    return GroupWrapper.open(uri, mode, context, timestamp)
  File "/home/ubuntu/anaconda3/envs/general-env/lib/python3.10/site-packages/tiledbsoma/_tdb_handles.py", line 85, in open
    tdb = cls._opener(uri, mode, context, timestamp_ms)
  File "/home/ubuntu/anaconda3/envs/general-env/lib/python3.10/site-packages/tiledbsoma/_tdb_handles.py", line 227, in _opener
    return tiledb.Group(uri, mode, ctx=ctx, config=tiledb.Config(cfgdict))
  File "/home/ubuntu/anaconda3/envs/general-env/lib/python3.10/site-packages/tiledb/group.py", line 270, in __init__
    super().__init__(ctx, uri, query_type, config)
  File "/home/ubuntu/anaconda3/envs/general-env/lib/python3.10/site-packages/tiledb/ctx.py", line 409, in __init__
    super().__init__(ctx, *args)
tiledb.cc.TileDBError: [TileDB::S3] Error: Failed to read S3 object s3://reducted_bucket/reducet_dataset/__group/
Exception:  InvalidRange
Error message:  Unable to parse ExceptionName: InvalidRange Message: The requested range is not satisfiable
```

**To Reproduce**
1. Create a SOMA experiment and write it to a s3 bucket.
2. Copy experiment to another s3 bucket.
3. Try to .open experiment from last bucket. 

**Versions (please complete the following information):**
 - TileDB-SOMA version: 1.4.4
 - Language and language version (e.g. Python 3.8, R 4.2.2): python 3.10
 - OS (e.g. MacOS, Ubuntu Linux): Ubuntu
 - Note: you can use `tiledbsoma.show_package_versions()` (Python) or `tiledbsoma::show_package_versions()` (R)

**Additional context**
After some investigation I think we got to the root cause. 
Apparently copying the s3 objects using datasync created additional objects in the destination bucket. 
So `s3://reducted_bucket/reducet_dataset/__group/` is not a prefix it's an actual object name. 

In order to solve the issue we had to delete any objects in the bucket the endswith "/"

During some attempts we did not manage to copy files using datasync without it creating the additional objects.

**Comment by johnkerl** [comment]
[[sc-53960]](https://app.shortcut.com/tiledb-inc/story/53960)
