### ISSUE TITLE
[python] pip install directly from GitHub not working

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#1991]
Installing from the repository remotely will fail to leave a functional package install.  I get the same failure on various branches (I tried `main` and `release-1.6`.

There is a workaround:  install with `pip install -e`

Demo:
```
$ python -m venv ./venv-test2
$ source ./venv-test2/bin/activate
(venv-test2) $ pip install 'git+https://github.com/single-cell-data/TileDB-SOMA.git#egg=tiledbsoma&subdirectory=apis/python/'
Collecting tiledbsoma
...[snip]...
(venv-test2) $ python -c 'import tiledbsoma; tiledbsoma.show_package_versions()'
Traceback (most recent call last):
  File "/home/bruce/projects/cellxgene-census/venv-test2/lib/python3.10/site-packages/tiledbsoma/_tiledb_array.py", line 34, in _load_libs
    ctypes.CDLL(os.path.join(lib_dir, lib_name))
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtiledb.so.2.18: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/bruce/projects/cellxgene-census/venv-test2/lib/python3.10/site-packages/tiledbsoma/__init__.py", line 104, in <module>
    from ._collection import Collection
  File "/home/bruce/projects/cellxgene-census/venv-test2/lib/python3.10/site-packages/tiledbsoma/_collection.py", line 36, in <module>
    from ._common_nd_array import NDArray
  File "/home/bruce/projects/cellxgene-census/venv-test2/lib/python3.10/site-packages/tiledbsoma/_common_nd_array.py", line 18, in <module>
    from ._tiledb_array import TileDBArray
  File "/home/bruce/projects/cellxgene-census/venv-test2/lib/python3.10/site-packages/tiledbsoma/_tiledb_array.py", line 41, in <module>
    _load_libs()
  File "/home/bruce/projects/cellxgene-census/venv-test2/lib/python3.10/site-packages/tiledbsoma/_tiledb_array.py", line 37, in _load_libs
    ctypes.CDLL(lib_name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtiledbsoma.so: cannot open shared object file: No such file or directory
```

The shared libs appear to have been placed into the correct place, but don't load:
```
$ ls -l venv-test2/lib/python3.10/site-packages/tiledbsoma/
total 2484
-rw-rw-r-- 1 bruce bruce    9686 Dec 18 11:17 _arrow_types.py
-rw-rw-r-- 1 bruce bruce   27269 Dec 18 11:17 _collection.py
-rw-rw-r-- 1 bruce bruce    6830 Dec 18 11:17 _common_nd_array.py
-rw-rw-r-- 1 bruce bruce     345 Dec 18 11:17 _constants.py
-rw-rw-r-- 1 bruce bruce   38815 Dec 18 11:17 _dataframe.py
-rw-rw-r-- 1 bruce bruce    7982 Dec 18 11:17 _dense_nd_array.py
-rw-rw-r-- 1 bruce bruce    3096 Dec 18 11:17 eta.py
-rw-rw-r-- 1 bruce bruce    1522 Dec 18 11:17 _exception.py
-rw-rw-r-- 1 bruce bruce    2639 Dec 18 11:17 _experiment.py
-rw-rw-r-- 1 bruce bruce    1492 Dec 18 11:17 experiment_query.py
-rw-rw-r-- 1 bruce bruce    6792 Dec 18 11:17 _factory.py
-rw-rw-r-- 1 bruce bruce    4436 Dec 18 11:17 _funcs.py
-rw-rw-r-- 1 bruce bruce    1753 Dec 18 11:17 _general_utilities.py
-rw-rw-r-- 1 bruce bruce    5503 Dec 18 11:17 __init__.py
drwxrwxr-x 4 bruce bruce    4096 Dec 18 11:17 io
-rw-rw-r-- 1 bruce bruce 1451672 Dec 18 11:17 libtiledbsoma.so
-rw-rw-r-- 1 bruce bruce    2065 Dec 18 11:17 logging.py
-rw-rw-r-- 1 bruce bruce    3235 Dec 18 11:17 _measurement.py
drwxrwxr-x 3 bruce bruce    4096 Dec 18 11:17 options
drwxrwxr-x 2 bruce bruce    4096 Dec 18 11:17 __pycache__
-rwxrwxr-x 1 bruce bruce  792992 Dec 18 11:17 pytiledbsoma.cpython-310-x86_64-linux-gnu.so
-rw-rw-r-- 1 bruce bruce     133 Dec 18 11:17 py.typed
-rw-rw-r-- 1 bruce bruce   18234 Dec 18 11:17 _query_condition.py
-rw-rw-r-- 1 bruce bruce   18770 Dec 18 11:17 _read_iters.py
-rw-rw-r-- 1 bruce bruce   23731 Dec 18 11:17 _sparse_nd_array.py
-rw-rw-r-- 1 bruce bruce   12846 Dec 18 11:17 _tdb_handles.py
-rw-rw-r-- 1 bruce bruce    9389 Dec 18 11:17 _tiledb_array.py
-rw-rw-r-- 1 bruce bruce    9317 Dec 18 11:17 _tiledb_object.py
-rw-rw-r-- 1 bruce bruce    1499 Dec 18 11:17 _types.py
-rw-rw-r-- 1 bruce bruce    9107 Dec 18 11:17 _util.py
```

Note that the permissions on `libtiledbsoma.so` seem incorrect. But when I manually change them to 775, the package still fails to load.

**Comment by bkmartinjr** [comment]
Testing against the changes in PR #1937 - both `pip install` and `pip install -e` succeed.  At least in my hands, this issue is resolved by the PR.

**Comment by nguyenv** [comment]
Thanks for confirming. I will open a separate PR to close this issue.

**Comment by nguyenv** [comment]
I thought this would be very straightfoward, but I'll need to look at this some more next week. This does not seem to work once I rebase against `main` but haven't figured out why yet.
