### ISSUE TITLE
[Bug] Tracking flaky macOS CI: `dlopen … No such file` during `import libtiledbsoma`

### ISSUE THREAD

**Issue by ryan-williams** [single-cell-data/TileDB-SOMA#2237]
## Describe the bug
The "macos TILEDB_EXISTS: yes TILEDBSOMA_EXISTS: no" job sometimes fails, in the "Confirm linking to installed shared objects" step ([python-so-copying.yml#L232](https://github.com/single-cell-data/TileDB-SOMA/blob/0774b69f2cba5d8aa459d828f62cd9fe0d66c685/.github/workflows/python-so-copying.yml#L232)), with error:

```
OSError: dlopen(/Users/runner/work/TileDB-SOMA/TileDB-SOMA/venv-soma/lib/python3.11/site-packages/tiledbsoma/libtiledb.dylib, 0x000A): tried: '/Users/runner/work/TileDB-SOMA/TileDB-SOMA/venv-soma/lib/python3.11/site-packages/tiledbsoma/libtiledb.dylib' (no such file)
```

<details><summary>Example full stack trace</summary>

```
Traceback (most recent call last):
  File "/Users/runner/work/TileDB-SOMA/TileDB-SOMA/venv-soma/lib/python3.11/site-packages/tiledbsoma/__init__.py", line 104, in <module>
    from . import pytiledbsoma as clib
ImportError: dlopen(/Users/runner/work/TileDB-SOMA/TileDB-SOMA/venv-soma/lib/python3.11/site-packages/tiledbsoma/pytiledbsoma.cpython-311-darwin.so, 0x0002): Library not loaded: '@rpath/libtiledbsoma.dylib'
  Referenced from: '/Users/runner/work/TileDB-SOMA/TileDB-SOMA/venv-soma/lib/python3.11/site-packages/tiledbsoma/pytiledbsoma.cpython-311-darwin.so'
  Reason: tried: '/Users/runner/work/TileDB-SOMA/TileDB-SOMA/dist/lib/libtiledbsoma.dylib' (no such file), '/Users/runner/work/TileDB-SOMA/TileDB-SOMA/external/lib/libtiledbsoma.dylib' (no such file), '/Users/runner/work/TileDB-SOMA/TileDB-SOMA/dist/lib/libtiledbsoma.dylib' (no such file), '/Users/runner/work/TileDB-SOMA/TileDB-SOMA/external/lib/libtiledbsoma.dylib' (no such file), '/usr/lib/libtiledbsoma.dylib' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/runner/work/TileDB-SOMA/TileDB-SOMA/venv-soma/lib/python3.11/site-packages/tiledbsoma/__init__.py", line 118, in <module>
    ctypes.CDLL(os.path.join(lib_dir, libtiledb_name), mode=ctypes.RTLD_GLOBAL)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen(/Users/runner/work/TileDB-SOMA/TileDB-SOMA/venv-soma/lib/python3.11/site-packages/tiledbsoma/libtiledb.dylib, 0x000A): tried: '/Users/runner/work/TileDB-SOMA/TileDB-SOMA/venv-soma/lib/python3.11/site-packages/tiledbsoma/libtiledb.dylib' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/runner/work/TileDB-SOMA/TileDB-SOMA/venv-soma/lib/python3.11/site-packages/tiledbsoma/__init__.py", line 121, in <module>
    ctypes.CDLL(libtiledb_name, mode=ctypes.RTLD_GLOBAL)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ctypes/__init__.py", line [37](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/8191829188/job/22401948329?pr=2235#step:16:38)6, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen(libtiledb.dylib, 0x000A): tried: 'libtiledb.dylib' (no such file), '/usr/lib/libtiledb.dylib' (no such file), '/Users/runner/work/TileDB-SOMA/TileDB-SOMA/libtiledb.dylib' (no such file)
Error: Process completed with exit code 1.
```
</details> 

Running list of instances of this failure that I've noticed:
- [3/6/24](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/8180076623/job/22367393933?pr=2227#step:16:37) (@johnkerl)
- [3/7/24](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/8182105341/job/22372928875#step:16:37) (me)
- [3/7/24](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/8191829188/job/22401948329?pr=2235#step:16:37) (me)
- [3/15/24](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/8300380263/job/22718191691?pr=1960#step:16:37) (me)
- [3/21/24](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/8383229307/job/22958534492?pr=2256#step:16:48) (me)

In all cases, 1 re-run was sufficient to mine a successful run.

### Aside: mitigation + possible separate segfault issue
https://github.com/single-cell-data/TileDB-SOMA/pull/2229 should make it less common (by running the job in question less frequently/superfluously).

Note that a similar flaky CI job was observed there, by @jdblischak ([GHA link](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/8180364638/job/22368243175#step:4:78)), in job "macos TILEDB_EXISTS: yes TILEDBSOMA_EXISTS: yes", step [Build and install libtiledbsoma](https://github.com/single-cell-data/TileDB-SOMA/blob/92593fd72acb58ebb283f7e4391a7d2b426b92e4/.github/workflows/python-so-copying.yml#L155-L168):

```
clang: error: unable to execute command: Segmentation fault: 11
```

<details><summary>Full stack trace</summary>

```
-- Install prefix is /Users/runner/work/TileDB-SOMA/TileDB-SOMA/external.
-- The C compiler identification is AppleClang 14.0.0.14000029
-- The CXX compiler identification is AppleClang 14.0.0.14000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode_14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode_14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Starting TileDB-SOMA superbuild.
-- Found TileDB: /Users/runner/work/TileDB-SOMA/TileDB-SOMA/external/lib/libtiledb.dylib
-- Could NOT find spdlog (missing: spdlog_DIR)
-- Adding spdlog as an external project
-- Not found clang-tidy
-- Not found clang-format
-- Configuring done (4.4s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/runner/work/TileDB-SOMA/TileDB-SOMA/build-libtiledbsoma
/Users/runner/work/_temp/f7f53cdf-a50d-4785-9ee7-cb72edffd8d5.sh: line 8: nproc: command not found
[  6%] Creating directories for 'ep_spdlog'
[ 12%] Performing download step (download, verify and extract) for 'ep_spdlog'
-- ep_spdlog download command succeeded.  See also /Users/runner/work/TileDB-SOMA/TileDB-SOMA/build-libtiledbsoma/externals/src/ep_spdlog-stamp/ep_spdlog-download-*.log
[ 18%] No update step for 'ep_spdlog'
[ 25%] Performing patch step for 'ep_spdlog'
patching file include/spdlog/logger-inl.h
[ 31%] Performing configure step for 'ep_spdlog'
-- ep_spdlog configure command succeeded.  See also /Users/runner/work/TileDB-SOMA/TileDB-SOMA/build-libtiledbsoma/externals/src/ep_spdlog-stamp/ep_spdlog-configure-*.log
[ 37%] Performing build step for 'ep_spdlog'
CMake Error at /Users/runner/work/TileDB-SOMA/TileDB-SOMA/build-libtiledbsoma/externals/src/ep_spdlog-stamp/ep_spdlog-build-Release.cmake:37 (message):
-- stdout output is:
  Command failed: 2
[ 10%] Building CXX object CMakeFiles/spdlog.dir/src/spdlog.cpp.o

[ [20](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/8180364638/job/22368243175#step:4:21)%] Building CXX object CMakeFiles/spdlog.dir/src/stdout_sinks.cpp.o
   '/Applications/Xcode_14.2.app/Contents/Developer/usr/bin/make'
[ 30%] Building CXX object CMakeFiles/spdlog.dir/src/color_sinks.cpp.o

  See also

    /Users/runner/work/TileDB-SOMA/TileDB-SOMA/build-libtiledbsoma/externals/src/ep_spdlog-stamp/ep_spdlog-build-*.log


CMake Error at /Users/runner/work/TileDB-SOMA/TileDB-SOMA/build-libtiledbsoma/externals/src/ep_spdlog-stamp/ep_spdlog-build-Release.cmake:47 (message):
  Stopping after outputting logs.


make[2]: *** [externals/src/ep_spdlog-stamp/ep_spdlog-build] Error 1
make[1]: *** [CMakeFiles/ep_spdlog.dir/all] Error 2
make: *** [all] Error 2
[ 40%] Building CXX object CMakeFiles/spdlog.dir/src/file_sinks.cpp.o
[ 50%] Building CXX object CMakeFiles/spdlog.dir/src/async.cpp.o
[ 60%] Building CXX object CMakeFiles/spdlog.dir/src/cfg.cpp.o
[ 70%] Building CXX object CMakeFiles/spdlog.dir/src/fmt.cpp.o

-- stderr output is:
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin[21](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/8180364638/job/22368243175#step:4:22).6.0
Thread model: posix
InstalledDir: /Applications/Xcode_14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /var/folders/h1/8hndypj13nsbj5pn4xsnv1tm0000gn/T/spdlog-510f3d.cpp
clang: note: diagnostic msg: /var/folders/h1/8hndypj13nsbj5pn4xsnv1tm0000gn/T/spdlog-510f3d.sh
clang: note: diagnostic msg: Crash backtrace is located in
clang: note: diagnostic msg: /Users/runner/Library/Logs/DiagnosticReports/clang_<YYYY-MM-DD-HHMMSS>_<hostname>.crash
clang: note: diagnostic msg: (choose the .crash file that corresponds to your crash)
clang: note: diagnostic msg: 

********************
make[5]: *** [CMakeFiles/spdlog.dir/src/spdlog.cpp.o] Error [25](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/8180364638/job/22368243175#step:4:26)4
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [CMakeFiles/spdlog.dir/all] Error 2
make[3]: *** [all] Error 2

Error: Process completed with exit code 2.
```
</details>

Can file a separate issue for that, if we keep seeing it.

**Comment by ryan-williams** [comment]
Added one to the list above:
> - [3/15/24](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/8300380263/job/22718191691?pr=1960#step:16:37) (me)

**Comment by ryan-williams** [comment]
And another:
> - [3/21/24](https://github.com/single-cell-data/TileDB-SOMA/actions/runs/8383229307/job/22958534492?pr=2256#step:16:48) (me)

**Comment by jdblischak** [comment]
This flaky build error is so frustrating. I've been meaning to investigate further, and it just happened to me recently, so I took some time to compare a [failed build](https://github.com/jdblischak/TileDB-SOMA/actions/runs/8634070546/job/23668622294) with its [passing build](https://github.com/jdblischak/TileDB-SOMA/actions/runs/8634070546/job/23716169866) after a simple manual restart. I copy-pasted the raw logs, removed the timestamps, and compared.

To begin, in both the failing and passing builds, the required `libtiledbsoma.dylib` is in the same exact directory as `pytiledbsoma.cpython-311-darwin.so`, so it should be easy to find.

```sh
./venv-soma/lib/python3.11/site-packages/tiledbsoma/pytiledbsoma.cpython-311-darwin.so
./venv-soma/lib/python3.11/site-packages/tiledbsoma/libtiledbsoma.dylib
```

And the RPATH is identical in both the failing and passing builds: `@rpath/libtiledbsoma.dylib`

Next I `grep`'d for `libtiledbsoma.dylib` and `diff`'d the results.

<details>
<summary>
Results of diffing the passing and failing logs for all mentions of `libtiledbsoma.dylib`
</summary>


```sh
$ grep libtiledbsoma.dylib soma-failed.txt
[ 74%] Linking CXX shared library libtiledbsoma.dylib
-- Installing: /Users/runner/work/TileDB-SOMA/TileDB-SOMA/dist/lib/libtiledbsoma.dylib
Checking: /Users/runner/work/TileDB-SOMA/TileDB-SOMA/dist/lib/libtiledbsoma.dylib exists: False
dlopen(libtiledbsoma.dylib, 0x0006): tried: 'libtiledbsoma.dylib' (no such file), '/usr/lib/libtiledbsoma.dylib' (no such file), '/Users/runner/work/TileDB-SOMA/TileDB-SOMA/apis/python/libtiledbsoma.dylib' (no such file)
Checking: /Users/runner/work/TileDB-SOMA/TileDB-SOMA/dist/lib/libtiledbsoma.dylib exists: True
  copying file /Users/runner/work/TileDB-SOMA/TileDB-SOMA/dist/lib/libtiledbsoma.dylib to /Users/runner/work/TileDB-SOMA/TileDB-SOMA/apis/python/src/tiledbsoma
  adding to package_data: ['libtiledbsoma.dylib']
copying src/tiledbsoma/libtiledbsoma.dylib -> build/lib.macosx-10.9-universal2-cpython-311/tiledbsoma
Checking: /Users/runner/work/TileDB-SOMA/TileDB-SOMA/dist/lib/libtiledbsoma.dylib exists: True
ld: warning: ignoring file /Users/runner/work/TileDB-SOMA/TileDB-SOMA/dist/lib/libtiledbsoma.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: dylib (/Users/runner/work/TileDB-SOMA/TileDB-SOMA/dist/lib/libtiledbsoma.dylib) was built for newer macOS version (12.7) than being linked (11.0)
copying build/lib.macosx-10.9-universal2-cpython-311/tiledbsoma/libtiledbsoma.dylib -> build/bdist.macosx-10.9-universal2/wheel/tiledbsoma
build/bdist.macosx-10.9-universal2/wheel/tiledbsoma/libtiledbsoma.dylib
build/bdist.macosx-10.9-universal2/wheel/tiledbsoma/libtiledbsoma.dylib
adding 'tiledbsoma/libtiledbsoma.dylib'
   989448  04-10-2024 15:52   tiledbsoma/libtiledbsoma.dylib
##[group]Run unzip -l apis/python/dist/tiledbsoma-*.whl | grep -q libtiledbsoma.dylib
unzip -l apis/python/dist/tiledbsoma-*.whl | grep -q libtiledbsoma.dylib
        @rpath/libtiledbsoma.dylib (compatibility version 0.0.0, current version 0.0.0)
./venv-soma/lib/python3.11/site-packages/tiledbsoma/libtiledbsoma.dylib
ImportError: dlopen(/Users/runner/work/TileDB-SOMA/TileDB-SOMA/venv-soma/lib/python3.11/site-packages/tiledbsoma/pytiledbsoma.cpython-311-darwin.so, 0x0002): Library not loaded: '@rpath/libtiledbsoma.dylib'
  Reason: tried: '/Users/runner/work/TileDB-SOMA/TileDB-SOMA/dist/lib/libtiledbsoma.dylib' (no such file), '/Users/runner/work/TileDB-SOMA/TileDB-SOMA/external/lib/libtiledbsoma.dylib' (no such file), '/Users/runner/work/TileDB-SOMA/TileDB-SOMA/dist/lib/libtiledbsoma.dylib' (no such file), '/Users/runner/work/TileDB-SOMA/TileDB-SOMA/external/lib/libtiledbsoma.dylib' (no such file), '/usr/lib/libtiledbsoma.dylib' (no such file)

$ grep libtiledbsoma.dylib soma-passed.txt
[ 71%] Linking CXX shared library libtiledbsoma.dylib
-- Installing: /Users/runner/work/TileDB-SOMA/TileDB-SOMA/dist/lib/libtiledbsoma.dylib
Checking: /Users/runner/work/TileDB-SOMA/TileDB-SOMA/dist/lib/libtiledbsoma.dylib exists: False
dlopen(libtiledbsoma.dylib, 0x0006): tried: '/Users/runner/work/TileDB-SOMA/TileDB-SOMA/external/lib/libtiledbsoma.dylib' (no such file), 'libtiledbsoma.dylib' (no such file), '/usr/local/lib/libtiledbsoma.dylib' (no such file), '/usr/lib/libtiledbsoma.dylib' (no such file), '/Users/runner/work/TileDB-SOMA/TileDB-SOMA/external/lib/libtiledbsoma.dylib' (no such file), '/Users/runner/work/TileDB-SOMA/TileDB-SOMA/apis/python/libtiledbsoma.dylib' (no such file)
Checking: /Users/runner/work/TileDB-SOMA/TileDB-SOMA/dist/lib/libtiledbsoma.dylib exists: True
  copying file /Users/runner/work/TileDB-SOMA/TileDB-SOMA/dist/lib/libtiledbsoma.dylib to /Users/runner/work/TileDB-SOMA/TileDB-SOMA/apis/python/src/tiledbsoma
  adding to package_data: ['libtiledbsoma.dylib']
copying src/tiledbsoma/libtiledbsoma.dylib -> build/lib.macosx-10.9-universal2-cpython-311/tiledbsoma
Checking: /Users/runner/work/TileDB-SOMA/TileDB-SOMA/dist/lib/libtiledbsoma.dylib exists: True
ld: warning: ignoring file /Users/runner/work/TileDB-SOMA/TileDB-SOMA/dist/lib/libtiledbsoma.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: dylib (/Users/runner/work/TileDB-SOMA/TileDB-SOMA/dist/lib/libtiledbsoma.dylib) was built for newer macOS version (12.7) than being linked (11.0)
build/bdist.macosx-10.9-universal2/wheel/tiledbsoma/libtiledbsoma.dylib
copying build/lib.macosx-10.9-universal2-cpython-311/tiledbsoma/libtiledbsoma.dylib -> build/bdist.macosx-10.9-universal2/wheel/tiledbsoma
build/bdist.macosx-10.9-universal2/wheel/tiledbsoma/libtiledbsoma.dylib
adding 'tiledbsoma/libtiledbsoma.dylib'
  1005848  04-11-2024 15:52   tiledbsoma/libtiledbsoma.dylib
##[group]Run unzip -l apis/python/dist/tiledbsoma-*.whl | grep -q libtiledbsoma.dylib
unzip -l apis/python/dist/tiledbsoma-*.whl | grep -q libtiledbsoma.dylib
        @rpath/libtiledbsoma.dylib (compatibility version 0.0.0, current version 0.0.0)
./venv-soma/lib/python3.11/site-packages/tiledbsoma/libtiledbsoma.dylib

$ diff <(grep libtiledbsoma.dylib soma-failed.txt) <(grep libtiledbsoma.dylib soma-passed.txt)
1c1
< [ 74%] Linking CXX shared library libtiledbsoma.dylib
---
> [ 71%] Linking CXX shared library libtiledbsoma.dylib
4c4
< dlopen(libtiledbsoma.dylib, 0x0006): tried: 'libtiledbsoma.dylib' (no such file), '/usr/lib/libtiledbsoma.dylib' (no such file), '/Users/runner/work/TileDB-SOMA/TileDB-SOMA/apis/python/libtiledbsoma.dylib' (no such file)
---
> dlopen(libtiledbsoma.dylib, 0x0006): tried: '/Users/runner/work/TileDB-SOMA/TileDB-SOMA/external/lib/libtiledbsoma.dylib' (no such file), 'libtiledbsoma.dylib' (no such file), '/usr/local/lib/libtiledbsoma.dylib' (no such file), '/usr/lib/libtiledbsoma.dylib' (no such file), '/Users/runner/work/TileDB-SOMA/TileDB-SOMA/external/lib/libtiledbsoma.dylib' (no such file), '/Users/runner/work/TileDB-SOMA/TileDB-SOMA/apis/python/libtiledbsoma.dylib' (no such file)
12d11
< copying build/lib.macosx-10.9-universal2-cpython-311/tiledbsoma/libtiledbsoma.dylib -> build/bdist.macosx-10.9-universal2/wheel/tiledbsoma
13a13
> copying build/lib.macosx-10.9-universal2-cpython-311/tiledbsoma/libtiledbsoma.dylib -> build/bdist.macosx-10.9-universal2/wheel/tiledbsoma
16c16
<    989448  04-10-2024 15:52   tiledbsoma/libtiledbsoma.dylib
---
>   1005848  04-11-2024 15:52   tiledbsoma/libtiledbsoma.dylib
21,22d20
< ImportError: dlopen(/Users/runner/work/TileDB-SOMA/TileDB-SOMA/venv-soma/lib/python3.11/site-packages/tiledbsoma/pytiledbsoma.cpython-311-darwin.so, 0x0002): Library not loaded: '@rpath/libtiledbsoma.dylib'
<   Reason: tried: '/Users/runner/work/TileDB-SOMA/TileDB-SOMA/dist/lib/libtiledbsoma.dylib' (no such file), '/Users/runner/work/TileDB-SOMA/TileDB-SOMA/external/lib/libtiledbsoma.dylib' (no such file), '/Users/runner/work/TileDB-SOMA/TileDB-SOMA/dist/lib/libtiledbsoma.dylib' (no such file), '/Users/runner/work/TileDB-SOMA/TileDB-SOMA/external/lib/libtiledbsoma.dylib' (no such file), '/usr/lib/libtiledbsoma.dylib' (no such file)
```

</details>

The main difference I observed was that when `setup.py` initially searches for an existing `libtiledbsoma.dylib` (and in this instance we know it doesn't exist and has to be built from source), the passing job searches in more locations, including `external/lib` (where `libtiledb.dylib` is installed).

https://github.com/single-cell-data/TileDB-SOMA/blob/0fc3cc0550389d7aaf0a758e03bc7bc65030b535/apis/python/setup.py#L132-L136

```python
# failed
Checking: /Users/runner/work/TileDB-SOMA/TileDB-SOMA/dist/lib/libtiledbsoma.dylib exists: False
dlopen(libtiledbsoma.dylib, 0x0006): tried: 'libtiledbsoma.dylib' (no such file), '/usr/lib/libtiledbsoma.dylib' (no such file), '/Users/runner/work/TileDB-SOMA/TileDB-SOMA/apis/python/libtiledbsoma.dylib' (no such file)
Checking: /Users/runner/work/TileDB-SOMA/TileDB-SOMA/dist/lib/libtiledbsoma.dylib exists: True
  copying file /Users/runner/work/TileDB-SOMA/TileDB-SOMA/dist/lib/libtiledbsoma.dylib to /Users/runner/work/TileDB-SOMA/TileDB-SOMA/apis/python/src/tiledbsoma
  adding to package_data: ['libtiledbsoma.dylib']

# passed
Checking: /Users/runner/work/TileDB-SOMA/TileDB-SOMA/dist/lib/libtiledbsoma.dylib exists: False
dlopen(libtiledbsoma.dylib, 0x0006): tried: '/Users/runner/work/TileDB-SOMA/TileDB-SOMA/external/lib/libtiledbsoma.dylib' (no such file), 'libtiledbsoma.dylib' (no such file), '/usr/local/lib/libtiledbsoma.dylib' (no such file), '/usr/lib/libtiledbsoma.dylib' (no such file), '/Users/runner/work/TileDB-SOMA/TileDB-SOMA/external/lib/libtiledbsoma.dylib' (no such file), '/Users/runner/work/TileDB-SOMA/TileDB-SOMA/apis/python/libtiledbsoma.dylib' (no such file)
Checking: /Users/runner/work/TileDB-SOMA/TileDB-SOMA/dist/lib/libtiledbsoma.dylib exists: True
  copying file /Users/runner/work/TileDB-SOMA/TileDB-SOMA/dist/lib/libtiledbsoma.dylib to /Users/runner/work/TileDB-SOMA/TileDB-SOMA/apis/python/src/tiledbsoma
  adding to package_data: ['libtiledbsoma.dylib']
```

So given that, maybe the primary error isn't finding `libtiledbsoma.dylib` installed in the Python package, but instead finding the external `libtiledb.dylib` installed in `external/lib`.  As we can see from the error from `cytpes.CDLL()`, it is not even looking in `external/lib` for `libtiledb.dylib`.

```python
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/runner/work/TileDB-SOMA/TileDB-SOMA/venv-soma/lib/python3.11/site-packages/tiledbsoma/__init__.py", line 118, in <module>
    ctypes.CDLL(os.path.join(lib_dir, libtiledb_name), mode=ctypes.RTLD_GLOBAL)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen(/Users/runner/work/TileDB-SOMA/TileDB-SOMA/venv-soma/lib/python3.11/site-packages/tiledbsoma/libtiledb.dylib, 0x000A): tried: '/Users/runner/work/TileDB-SOMA/TileDB-SOMA/venv-soma/lib/python3.11/site-packages/tiledbsoma/libtiledb.dylib' (no such file)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/runner/work/TileDB-SOMA/TileDB-SOMA/venv-soma/lib/python3.11/site-packages/tiledbsoma/__init__.py", line 121, in <module>
    ctypes.CDLL(libtiledb_name, mode=ctypes.RTLD_GLOBAL)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen(libtiledb.dylib, 0x000A): tried: 'libtiledb.dylib' (no such file), '/usr/lib/libtiledb.dylib' (no such file), '/Users/runner/work/TileDB-SOMA/TileDB-SOMA/libtiledb.dylib' (no such file)
```

But why is the search path different between the initial failing run and its passing restarted run?

**Comment by eddelbuettel** [comment]
Nice find.  

For the record it also bit me maybe four or five times last week when working on `nanoarrow` (and triggering Python CI).

**Comment by jdblischak** [comment]
I think the problem is macOS's [System Integrity Protection](https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection). From https://github.com/pypa/cibuildwheel/issues/816#issuecomment-916197079:

> macOS strips that env var out after each subprocess launch

Looking again at my failing build, I can see that `DYLD_LIBRARY_PATH` is set both [during the wheel build](https://github.com/jdblischak/TileDB-SOMA/actions/runs/8634070546/job/23668622294#step:7:7) and later [during the failed runtime step](https://github.com/jdblischak/TileDB-SOMA/actions/runs/8634070546/job/23668622294#step:16:9). So I guess sometimes SIP is applied and sometimes not.

I'm at a bit of a loss on how to proceed here. I can literally see that I have properly set `DYLD_LIBRARY_PATH` in the workflow, but SIP randomly unsets it only some of the time. How can I write a robust workflow to run on macOS when it is actively making it difficult to find shared libraries?

![image](https://github.com/single-cell-data/TileDB-SOMA/assets/1608317/42c27b5d-552a-4ce1-bede-3e583dbf9cfe)
