### ISSUE TITLE
[Bug] DataFrame object has no attribute `shape` when running ExperimentAxis Query

### ISSUE THREAD

**Issue by mdylan2** [single-cell-data/TileDB-SOMA#2454]
**Description:**
When trying to fetch obsm_layers using ExperimentAxisQuery syntax, I get the error below:
```Traceback (most recent call last):
  File ".../test_tiledb_pipeline_dummy copy.py", line 135, in <module>
    anndata = query.to_anndata(X_name="X", obsm_layers=("umap",))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/somacore/query/query.py", line 295, in to_anndata
    return self._read(
           ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/somacore/query/query.py", line 424, in _read
    obsm=obsm_ft.result(),
         ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/somacore/query/query.py", line 385, in _read_axis_mappings
    return {key: fn(axis, key) for key in keys}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/somacore/query/query.py", line 385, in <dictcomp>
    return {key: fn(axis, key) for key in keys}
                 ^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/somacore/query/query.py", line 571, in _axism_inner_ndarray
    _, n_col = axism[layer].shape
               ^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'shape'
```

**To Reproduce**
```import tiledbsoma as soma
import shutil
import pandas as pd
import pyarrow as pa
import scipy.sparse as sp

soma_path = "./corpus"
sample_1 = {
    "barcode": [
        "A",
        "B",
        "C",
    ],
    "features": [
        "CD8",
        "CD4",
    ],
    "matrix": [
        [1, 0],
        [0, 1],
        [1, 1],
    ],
    "obsm": [
        [0.1, 0.2],
        [0.3, 0.1],
        [0.0, 0.8]
    ]
}

# SCHEMAS
obs_schema = [
    ("soma_joinid", pa.int64()),
    ("barcode", pa.large_string())
]
var_schema = [
    ("soma_joinid", pa.int64()),
    ("gene_name", pa.large_string())
]
obsm_schema = [
    ("soma_joinid", pa.int64()),
    ("umap_0", pa.float32()),
    ("umap_1", pa.float32()),
]

# Create experiment
exp = soma.Experiment.create(soma_path)
exp.close()

# Open experiment for reading
with soma.Experiment.open(soma_path, mode="w") as exp:
    ms = exp.add_new_collection("ms")
    rna = ms.add_new_collection("RNA", soma.Measurement)
    X_collection = rna.add_new_collection("X")
    X_collection.add_new_sparse_ndarray(
        "X",
        type=pa.uint32(),
        shape=(3, 2),
    )
    rna.add_new_dataframe("var", schema=pa.schema(var_schema))
    obsm_coll = rna.add_new_collection("obsm")
    obsm_coll.add_new_dataframe("umap", schema=pa.schema(obsm_schema))
    exp.add_new_dataframe("obs", schema=pa.schema(obs_schema))

    ms.close()
    rna.close()
    obsm_coll.close()
    X_collection.close()

current_obs_id = 0
current_var_id = 0
for i, dict_ in enumerate([sample_1,]):
    # Obs ingest
    sub_obs = pd.DataFrame(dict_["barcode"], columns=["barcode"])
    sub_obs["soma_joinid"] = range(current_obs_id, current_obs_id + len(sub_obs))
    pa_table = pa.Table.from_pandas(
        sub_obs, 
        schema=pa.schema(obs_schema), 
    )
    with soma.Experiment.open(soma_path, mode="w") as exp:
        exp.obs.write(
            pa_table
        )
    
    # Var ingest
    sub_var = pd.DataFrame(dict_["features"], columns=["gene_name"])
    sub_var["soma_joinid"] = range(current_var_id, current_var_id + len(sub_var))
    pa_table = pa.Table.from_pandas(
        sub_var, 
        schema=pa.schema(var_schema), 
    )
    with soma.Experiment.open(soma_path, mode="w") as exp:
        exp.ms["RNA"].var.write(
            pa_table
        )
    
    # X ingest
    matrix = sp.coo_matrix(dict_["matrix"], shape=(3, 2))
    with soma.Experiment.open(soma_path, mode="w") as exp:
        exp.ms["RNA"]["X"]["X"].write(
            pa.Table.from_pydict(
                {
                    "soma_dim_0": matrix.row + current_obs_id,
                    "soma_dim_1": matrix.col + current_var_id,
                    "soma_data": matrix.data

                }
            )
        )

    # Obsm ingest
    sub_obsm = pd.DataFrame(dict_["obsm"], columns=["umap_0", "umap_1"])
    sub_obsm["soma_joinid"] = range(current_obs_id, current_obs_id + len(sub_obsm))
    pa_table = pa.Table.from_pandas(
        sub_obsm, 
        schema=pa.schema(obsm_schema), 
    )
    with soma.Experiment.open(soma_path, mode="w") as exp:
        exp.ms["RNA"]["obsm"]["umap"].write(
            pa_table
        )
    

with soma.Experiment.open(soma_path) as exp:
    with exp.axis_query(measurement_name="RNA") as query:
        anndata = query.to_anndata(X_name="X", obsm_layers=("umap",))
        print(anndata)
```

**Versions:**
 - TileDB-SOMA version: 1.10.0
 - Language and language version (e.g. Python 3.8, R 4.2.2): Python 3.11.6
 - OS (e.g. MacOS, Ubuntu Linux): MacOS M1

**Comment by johnkerl** [comment]
[sc-46789]

**Comment by johnkerl** [comment]
@mdylan2 `obsm` entries should be `SparseNDArray` (or `DenseNDArray`) -- having `DataFrame` here should not be supported.

That said, we should have errored out at a much higher level, with a more intuitive error message. I'll fix this.

**Comment by mdylan2** [comment]
I think we can switch over to Sparse/Dense ND Array. There's no particular need for the DataFrame.

The only issue was dealing with empty rows but I think Dense/SparseNDArrays have row/column indices so we should be fine

**Comment by johnkerl** [comment]
> The only issue was dealing with empty rows but I think Dense/SparseNDArrays have row/column indices so we should be fine

@mdylan2 indeed -- `obsm` array rows are keyed by the `soma_joinid` of `obs`, always

**Comment by johnkerl** [comment]
> I think we can switch over to Sparse/Dense ND Array. There's no particular need for the DataFrame.
> 
> The only issue was dealing with empty rows but I think Dense/SparseNDArrays have row/column indices so we should be fine

Awesome, thanks @mdylan2 !
