### ISSUE TITLE
[Bug] Incorrect install requirements on the latest tiledbsoma 1.12.0

### ISSUE THREAD

**Issue by Koncopd** [single-cell-data/TileDB-SOMA#2758]
`pip install tiledbsoma`
installed `tiledb` 0.30.1
and then importing 
`import tiledbsoma.io`
gives
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/koncopd/miniconda3/envs/work39/lib/python3.9/site-packages/tiledbsoma/__init__.py", line 180, in <module>
    verify_core_versions()
  File "/home/koncopd/miniconda3/envs/work39/lib/python3.9/site-packages/tiledbsoma/_general_utilities.py", line 128, in verify_core_versions
    raise AssertionError(
AssertionError: libtiledb versions used by tiledb and libtiledbsoma differ: 2.24.1 != 2.24.0
```
installing `tiledb` 0.30.0 manually solves the problem

**Comment by johnkerl** [comment]
@Koncopd thanks! We will make a 12.0.1 with tiledb-py 0.30.1.

**Comment by johnkerl** [comment]
See also #2672

**Comment by johnkerl** [comment]
https://github.com/single-cell-data/TileDB-SOMA/pull/2759

**Comment by johnkerl** [comment]
Resolved by
https://github.com/single-cell-data/TileDB-SOMA/releases/tag/1.12.1
https://pypi.org/project/tiledbsoma/1.12.1/

```
$ pip install tiledbsoma
...
$ python
...
>>> import tiledbsoma
>>> tiledbsoma.show_package_versions()
tiledbsoma.__version__              1.12.1
TileDB-Py version                   0.30.1
TileDB core version (tiledb)        2.24.1
TileDB core version (libtiledbsoma) 2.24.1
python version                      3.10.14.final.0
OS version                          Linux 6.5.0-1020-aws
```
