### ISSUE TITLE
Py tiledbsoma build issues 

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#306]
I just created a fresh clone and Python virtual environment, to catch up on all of the recent reorg.  Initial attempts to build generated some errors.  In summary:
* there is a requirement for a very recent `cmake` - would be good to list this in the build README
* there is no python `requirements.txt`, so I made a guess at what packages must be pre-installed.  Would be good to add such a file (or equivalent), to make build bootstrap simpler.
* the initial attempt to run `python setup.py develop` failed with a setuptools error:
    > ERROR: setuptools==44.1.1 is used in combination with setuptools_scm>=6.x
    > Your build configuration is incomplete and previously worked by accident! setuptools_scm requires setuptools>=45
* I then updated setuptools to latest (which was flagged by pip as incompatible), but...the build then worked.

So it looks like there is some package incompatibilities and/or messiness that could be improved over time.

Details:
 
```
$ pwd
/home/bruce/projects/TileDB-SOMA/apis/python
(venv) bruce@neigh:~/projects/TileDB-SOMA/apis/python$ python setup.py develop
/home/bruce/projects/TileDB-SOMA/apis/python/.eggs/setuptools_scm-7.0.5-py3.9.egg/setuptools_scm/integration.py:27: RuntimeWarning: 
ERROR: setuptools==44.1.1 is used in combination with setuptools_scm>=6.x

Your build configuration is incomplete and previously worked by accident!
setuptools_scm requires setuptools>=45


This happens as setuptools is unable to replace itself when a activated build dependency
requires a more recent setuptools version
(it does not respect "setuptools>X" in setup_requires).


setuptools>=31 is required for setup.cfg metadata support
setuptools>=42 is required for pyproject.toml configuration support

Suggested workarounds if applicable:
 - preinstalling build dependencies like setuptools_scm before running setup.py
 - installing setuptools_scm using the system package manager to ensure consistency
 - migrating from the deprecated setup_requires mechanism to pep517/518
   and using a pyproject.toml to declare build dependencies
   which are reliably pre-installed before running the build tools

  warnings.warn(
running develop
Traceback (most recent call last):
  File "/home/bruce/projects/TileDB-SOMA/apis/python/setup.py", line 91, in <module>
    setup(
  File "/home/bruce/projects/TileDB-SOMA/venv/lib/python3.9/site-packages/setuptools/__init__.py", line 162, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.9/distutils/dist.py", line 984, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python3.9/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/home/bruce/projects/TileDB-SOMA/venv/lib/python3.9/site-packages/setuptools/command/develop.py", line 56, in finalize_options
    easy_install.finalize_options(self)
  File "/home/bruce/projects/TileDB-SOMA/venv/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 296, in finalize_options
    self._expand(
  File "/home/bruce/projects/TileDB-SOMA/venv/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 1413, in _expand
    config_vars = self.get_finalized_command('install').config_vars
  File "/usr/lib/python3.9/distutils/cmd.py", line 299, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python3.9/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/home/bruce/projects/TileDB-SOMA/venv/lib/python3.9/site-packages/setuptools/command/install.py", line 38, in finalize_options
    orig.install.finalize_options(self)
  File "/usr/lib/python3.9/distutils/command/install.py", line 389, in finalize_options
    self.set_undefined_options('build',
  File "/usr/lib/python3.9/distutils/cmd.py", line 286, in set_undefined_options
    src_cmd_obj = self.distribution.get_command_obj(src_cmd)
  File "/usr/lib/python3.9/distutils/dist.py", line 857, in get_command_obj
    klass = self.get_command_class(command)
  File "/home/bruce/projects/TileDB-SOMA/venv/lib/python3.9/site-packages/setuptools/dist.py", line 834, in get_command_class
    self.cmdclass[command] = cmdclass = ep.load()
  File "/home/bruce/projects/TileDB-SOMA/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/bruce/projects/TileDB-SOMA/venv/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'setuptools.command.build'
$ pip install -U setuptools_scm wheel setuptools
Collecting setuptools_scm
  Using cached setuptools_scm-7.0.5-py3-none-any.whl (42 kB)
Requirement already satisfied: wheel in /home/bruce/projects/TileDB-SOMA/venv/lib/python3.9/site-packages (0.37.1)
Requirement already satisfied: setuptools in /home/bruce/projects/TileDB-SOMA/venv/lib/python3.9/site-packages (59.8.0)
Collecting setuptools
  Using cached setuptools-65.3.0-py3-none-any.whl (1.2 MB)
Requirement already satisfied: typing-extensions in /home/bruce/projects/TileDB-SOMA/venv/lib/python3.9/site-packages (from setuptools_scm) (4.3.0)
Requirement already satisfied: tomli>=1.0.0 in /home/bruce/projects/TileDB-SOMA/venv/lib/python3.9/site-packages (from setuptools_scm) (2.0.1)
Requirement already satisfied: packaging>=20.0 in /home/bruce/projects/TileDB-SOMA/venv/lib/python3.9/site-packages (from setuptools_scm) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/bruce/projects/TileDB-SOMA/venv/lib/python3.9/site-packages (from packaging>=20.0->setuptools_scm) (3.0.9)
Installing collected packages: setuptools, setuptools_scm
  Attempting uninstall: setuptools
    Found existing installation: setuptools 59.8.0
    Uninstalling setuptools-59.8.0:
      Successfully uninstalled setuptools-59.8.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.56.2 requires setuptools<60, but you have setuptools 65.3.0 which is incompatible.
Successfully installed setuptools-65.3.0 setuptools_scm-7.0.5
```

After this, the build worked, despite the above protestations.

**Comment by bkmartinjr** [comment]
Another error while trying to bootstrap an AWS EC2 instance.  I believe that the build requires the Python dev package to be installed, and this is missing from the build instructions.

```
CMake Error in src/pyapi/CMakeLists.txt:
  Imported target "pybind11::module" includes non-existent path

    "/usr/include/python3.9"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.
 
  * An install or uninstall procedure did not complete successfully. 
 
  * The installation package was faulty and references files it does not provide.
 ```

**Comment by bkmartinjr** [comment]
Another missing dep: a recent (C++ 20) compiler.  Eg, g++ 10 or 11

**Comment by bkmartinjr** [comment]
These are all fixed.  Closing.
