### ISSUE TITLE
[Bug] pip error

### ISSUE THREAD

**Issue by bookSiYi1412** [single-cell-data/TileDB-SOMA#3291]
**Describe the bug**
An error occurred when I attempted to install the package using the command `pip install tiledbsoma` --verbose. The output is provided in the "Additional context" section.
**To Reproduce**
pip install tiledbsoma --verbose

**Versions (please complete the following information):**
 - TileDB-SOMA version: 1.14.5 and 1.13 else
 - Language and language version (e.g. Python 3.9, R 4.3.2): Python 3.10
 - OS (e.g. MacOS, Ubuntu Linux): Windows
 - Note: you can use `tiledbsoma.show_package_versions()` (Python) or `tiledbsoma::show_package_versions()` (R)

**Additional context**

> Collecting tiledbsoma
>   Using cached tiledbsoma-1.14.5.tar.gz (454 kB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... error
>   error: subprocess-exited-with-error
> 
>   × Getting requirements to build wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [31 lines of output]
>       Traceback (most recent call last):
>         File "D:\Administrator\miniconda3\envs\db\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
>           main()
>         File "D:\Administrator\miniconda3\envs\db\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>         File "D:\Administrator\miniconda3\envs\db\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
>           return hook(config_settings)
>         File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-bh1013wj\overlay\Lib\site-packages\setuptools\build_meta.py", line 333, in get_requires_for_build_wheel
>           return self._get_build_requires(config_settings, requirements=[])
>         File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-bh1013wj\overlay\Lib\site-packages\setuptools\build_meta.py", line 303, in _get_build_requires
>           self.run_setup()
>         File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-bh1013wj\overlay\Lib\site-packages\setuptools\build_meta.py", line 319, in run_setup
>           exec(code, locals())
>         File "<string>", line 347, in <module>
>         File "C:\Users\Administrator\AppData\Local\Temp\pip-install-zs5tt3pw\tiledbsoma_465118cdfe714d2fb1a62e9606d11ce6\version.py", line 274, in get_version
>           version = get_git_version()
>         File "C:\Users\Administrator\AppData\Local\Temp\pip-install-zs5tt3pw\tiledbsoma_465118cdfe714d2fb1a62e9606d11ce6\version.py", line 189, in get_git_version
>           git_root = line("git", "rev-parse", "--show-toplevel")
>         File "C:\Users\Administrator\AppData\Local\Temp\pip-install-zs5tt3pw\tiledbsoma_465118cdfe714d2fb1a62e9606d11ce6\version.py", line 119, in line
>           lns = lines(*cmd, **kwargs)
>         File "C:\Users\Administrator\AppData\Local\Temp\pip-install-zs5tt3pw\tiledbsoma_465118cdfe714d2fb1a62e9606d11ce6\version.py", line 108, in lines
>           for ln in check_output(cmd, stderr=stderr, **kwargs).decode().splitlines()
>         File "D:\Administrator\miniconda3\envs\db\lib\subprocess.py", line 421, in check_output
>           return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>         File "D:\Administrator\miniconda3\envs\db\lib\subprocess.py", line 503, in run
>           with Popen(*popenargs, **kwargs) as process:
>         File "D:\Administrator\miniconda3\envs\db\lib\subprocess.py", line 971, in __init__
>           self._execute_child(args, executable, preexec_fn, close_fds,
>         File "D:\Administrator\miniconda3\envs\db\lib\subprocess.py", line 1456, in _execute_child
>           hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
>       FileNotFoundError: [WinError 2] 系统找不到指定的文件。
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.
> 
> (db) C:\Users\Administrator>python -m pip install tiledbsoma=1.13
> ERROR: Invalid requirement: 'tiledbsoma=1.13': Expected end or semicolon (after name and no valid version specifier)
>     tiledbsoma=1.13
>               ^
> Hint: = is not a valid operator. Did you mean == ?
> 
> (db) C:\Users\Administrator>python -m pip install tiledbsoma==1.13
> Collecting tiledbsoma==1.13
>   Downloading tiledbsoma-1.13.0.tar.gz (428 kB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... error
>   error: subprocess-exited-with-error
> 
>   × Getting requirements to build wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [31 lines of output]
>       Traceback (most recent call last):
>         File "D:\Administrator\miniconda3\envs\db\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
>           main()
>         File "D:\Administrator\miniconda3\envs\db\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>         File "D:\Administrator\miniconda3\envs\db\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
>           return hook(config_settings)
>         File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-fg83ntgh\overlay\Lib\site-packages\setuptools\build_meta.py", line 333, in get_requires_for_build_wheel
>           return self._get_build_requires(config_settings, requirements=[])
>         File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-fg83ntgh\overlay\Lib\site-packages\setuptools\build_meta.py", line 303, in _get_build_requires
>           self.run_setup()
>         File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-fg83ntgh\overlay\Lib\site-packages\setuptools\build_meta.py", line 319, in run_setup
>           exec(code, locals())
>         File "<string>", line 354, in <module>
>         File "C:\Users\Administrator\AppData\Local\Temp\pip-install-lrk2sw9l\tiledbsoma_753006e387d044f5ae68a387548e45ef\version.py", line 274, in get_version
>           version = get_git_version()
>         File "C:\Users\Administrator\AppData\Local\Temp\pip-install-lrk2sw9l\tiledbsoma_753006e387d044f5ae68a387548e45ef\version.py", line 189, in get_git_version
>           git_root = line("git", "rev-parse", "--show-toplevel")
>         File "C:\Users\Administrator\AppData\Local\Temp\pip-install-lrk2sw9l\tiledbsoma_753006e387d044f5ae68a387548e45ef\version.py", line 119, in line
>           lns = lines(*cmd, **kwargs)
>         File "C:\Users\Administrator\AppData\Local\Temp\pip-install-lrk2sw9l\tiledbsoma_753006e387d044f5ae68a387548e45ef\version.py", line 108, in lines
>           for ln in check_output(cmd, stderr=stderr, **kwargs).decode().splitlines()
>         File "D:\Administrator\miniconda3\envs\db\lib\subprocess.py", line 421, in check_output
>           return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>         File "D:\Administrator\miniconda3\envs\db\lib\subprocess.py", line 503, in run
>           with Popen(*popenargs, **kwargs) as process:
>         File "D:\Administrator\miniconda3\envs\db\lib\subprocess.py", line 971, in __init__
>           self._execute_child(args, executable, preexec_fn, close_fds,
>         File "D:\Administrator\miniconda3\envs\db\lib\subprocess.py", line 1456, in _execute_child
>           hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
>       FileNotFoundError: [WinError 2] 系统找不到指定的文件。
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.
> 
> (db) C:\Users\Administrator>pip uninstall tiledbsoma
> WARNING: Skipping tiledbsoma as it is not installed.
> 
> (db) C:\Users\Administrator>pip uninstall tiledb
> Found existing installation: tiledb 0.29.0
> Uninstalling tiledb-0.29.0:
>   Would remove:
>     d:\administrator\miniconda3\envs\db\lib\site-packages\ci
>     d:\administrator\miniconda3\envs\db\lib\site-packages\examples
>     d:\administrator\miniconda3\envs\db\lib\site-packages\external
>     d:\administrator\miniconda3\envs\db\lib\site-packages\misc
>     d:\administrator\miniconda3\envs\db\lib\site-packages\tiledb
>     d:\administrator\miniconda3\envs\db\lib\site-packages\tiledb-0.29.0-py3.10.egg-info
> Proceed (Y/n)? y
>   Successfully uninstalled tiledb-0.29.0
> 
> (db) C:\Users\Administrator>pip uninstall tiledbsoma --verbose
> WARNING: Skipping tiledbsoma as it is not installed.
> 
> (db) C:\Users\Administrator>pip install tiledbsoma --verbose
> Using pip 24.2 from D:\Administrator\miniconda3\envs\db\lib\site-packages\pip (python 3.10)
> Collecting tiledbsoma
>   Using cached tiledbsoma-1.14.5.tar.gz (454 kB)
>   Running command pip subprocess to install build dependencies
>   Using pip 24.2 from D:\Administrator\miniconda3\envs\db\Lib\site-packages\pip (python 3.10)
>   Collecting pybind11>=2.10.0 (from pybind11[global]>=2.10.0)
>     Obtaining dependency information for pybind11>=2.10.0 from https://files.pythonhosted.org/packages/13/2f/0f24b288e2ce56f51c920137620b4434a38fd80583dbbe24fc2a1656c388/pybind11-2.13.6-py3-none-any.whl.metadata
>     Using cached pybind11-2.13.6-py3-none-any.whl.metadata (9.5 kB)
>   Collecting setuptools>=65.5.1
>     Obtaining dependency information for setuptools>=65.5.1 from https://files.pythonhosted.org/packages/90/12/282ee9bce8b58130cb762fbc9beabd531549952cac11fc56add11dcb7ea0/setuptools-75.3.0-py3-none-any.whl.metadata
>     Using cached setuptools-75.3.0-py3-none-any.whl.metadata (6.9 kB)
>   Collecting wheel>=0.37.1
>     Obtaining dependency information for wheel>=0.37.1 from https://files.pythonhosted.org/packages/1b/d1/9babe2ccaecff775992753d8686970b1e2755d21c8a63be73aba7a4e7d77/wheel-0.44.0-py3-none-any.whl.metadata
>     Using cached wheel-0.44.0-py3-none-any.whl.metadata (2.3 kB)
>   Collecting cmake>=3.21
>     Obtaining dependency information for cmake>=3.21 from https://files.pythonhosted.org/packages/74/ed/6624adba772329c9c8a9765ee2ee06df7082ad7ac75cf33200d405c4c45f/cmake-3.30.5-py3-none-win_amd64.whl.metadata
>     Using cached cmake-3.30.5-py3-none-win_amd64.whl.metadata (6.4 kB)
>   Collecting pybind11-global==2.13.6 (from pybind11[global]>=2.10.0)
>     Obtaining dependency information for pybind11-global==2.13.6 from https://files.pythonhosted.org/packages/21/ee/8ab74ca797f609bc5563fb6989c02a0535d8b836c7ec6c45c8a37b19950f/pybind11_global-2.13.6-py3-none-any.whl.metadata
>     Using cached pybind11_global-2.13.6-py3-none-any.whl.metadata (9.4 kB)
>   Using cached pybind11-2.13.6-py3-none-any.whl (243 kB)
>   Using cached setuptools-75.3.0-py3-none-any.whl (1.3 MB)
>   Using cached wheel-0.44.0-py3-none-any.whl (67 kB)
>   Using cached cmake-3.30.5-py3-none-win_amd64.whl (35.6 MB)
>   Using cached pybind11_global-2.13.6-py3-none-any.whl (439 kB)
>   Installing collected packages: wheel, setuptools, pybind11-global, pybind11, cmake
>     Creating C:\Users\Administrator\AppData\Local\Temp\pip-build-env-t7w3a8or\overlay\Scripts
>   Successfully installed cmake-3.30.5 pybind11-2.13.6 pybind11-global-2.13.6 setuptools-75.3.0 wheel-0.44.0
>   Installing build dependencies ... done
>   Running command Getting requirements to build wheel
>   Traceback (most recent call last):
>     File "D:\Administrator\miniconda3\envs\db\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
>       main()
>     File "D:\Administrator\miniconda3\envs\db\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
>       json_out['return_val'] = hook(**hook_input['kwargs'])
>     File "D:\Administrator\miniconda3\envs\db\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
>       return hook(config_settings)
>     File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-t7w3a8or\overlay\Lib\site-packages\setuptools\build_meta.py", line 333, in get_requires_for_build_wheel
>       return self._get_build_requires(config_settings, requirements=[])
>     File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-t7w3a8or\overlay\Lib\site-packages\setuptools\build_meta.py", line 303, in _get_build_requires
>       self.run_setup()
>     File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-t7w3a8or\overlay\Lib\site-packages\setuptools\build_meta.py", line 319, in run_setup
>       exec(code, locals())
>     File "<string>", line 347, in <module>
>     File "C:\Users\Administrator\AppData\Local\Temp\pip-install-gtkujhka\tiledbsoma_1fc5027fb6c946c68d3537011612be26\version.py", line 274, in get_version
>       version = get_git_version()
>     File "C:\Users\Administrator\AppData\Local\Temp\pip-install-gtkujhka\tiledbsoma_1fc5027fb6c946c68d3537011612be26\version.py", line 189, in get_git_version
>       git_root = line("git", "rev-parse", "--show-toplevel")
>     File "C:\Users\Administrator\AppData\Local\Temp\pip-install-gtkujhka\tiledbsoma_1fc5027fb6c946c68d3537011612be26\version.py", line 119, in line
>       lns = lines(*cmd, **kwargs)
>     File "C:\Users\Administrator\AppData\Local\Temp\pip-install-gtkujhka\tiledbsoma_1fc5027fb6c946c68d3537011612be26\version.py", line 108, in lines
>       for ln in check_output(cmd, stderr=stderr, **kwargs).decode().splitlines()
>     File "D:\Administrator\miniconda3\envs\db\lib\subprocess.py", line 421, in check_output
>       return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>     File "D:\Administrator\miniconda3\envs\db\lib\subprocess.py", line 503, in run
>       with Popen(*popenargs, **kwargs) as process:
>     File "D:\Administrator\miniconda3\envs\db\lib\subprocess.py", line 971, in __init__
>       self._execute_child(args, executable, preexec_fn, close_fds,
>     File "D:\Administrator\miniconda3\envs\db\lib\subprocess.py", line 1456, in _execute_child
>       hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
>   FileNotFoundError: [WinError 2] 系统找不到指定的文件。
>   error: subprocess-exited-with-error
> 
>   × Getting requirements to build wheel did not run successfully.
>   │ exit code: 1
>   ╰─> See above for output.
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   full command: 'D:\Administrator\miniconda3\envs\db\python.exe' 'D:\Administrator\miniconda3\envs\db\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py' get_requires_for_build_wheel 'C:\Users\Administrator\AppData\Local\Temp\tmpbrocnbis'
>   cwd: C:\Users\Administrator\AppData\Local\Temp\pip-install-gtkujhka\tiledbsoma_1fc5027fb6c946c68d3537011612be26
>   Getting requirements to build wheel ... error
> error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by johnkerl** [comment]
@bookSiYi1412 thank you for your report!

Unfortunately, TileDB-SOMA is not yet supported on Windows.

**Comment by johnkerl** [comment]
Duplicate of #2631.
