### ISSUE TITLE
Follow up on dense SOMADataFrame objects

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#380]
Reproduce, triage, and propose a solution (if a problem still exists):

* https://github.com/single-cell-data/TileDB-SOMA/blob/main/apis/python/src/tiledbsoma/soma_dataframe.py#L97
* https://github.com/single-cell-data/TileDB-SOMA/blob/main/apis/python/src/tiledbsoma/soma_dataframe.py#L482

**Comment by johnkerl** [comment]
# Repro script

Repro script (adapted from [tests/test_soma_dataframe.py](https://github.com/single-cell-data/TileDB-SOMA/blob/c47314179c4d03c45db327ed9498129bfd4bc954/apis/python/tests/test_soma_dataframe.py)):

https://gist.github.com/johnkerl/bd9530ab73d4e4c99e5f5b04888d0ace

# Failure

Fails with:

```
Traceback (most recent call last):
  File "/Users/johnkerl/git/single-cell-data/TileDB-SOMA/apis/python/./repro.py", line 77, in <module>
    table = sdf.read_all(value_filter="foo == 40 or foo == 20")
  File "/Users/johnkerl/git/single-cell-data/TileDB-SOMA/apis/python/src/tiledbsoma/soma_dataframe.py", line 241, in read_all
    return pa.concat_tables(
  File "pyarrow/table.pxi", line 2623, in pyarrow.lib.concat_tables
  File "/Users/johnkerl/git/single-cell-data/TileDB-SOMA/apis/python/src/tiledbsoma/soma_dataframe.py", line 222, in read
    yield util_arrow.ascii_to_unicode_pyarrow_readback(table)
  File "/Users/johnkerl/git/single-cell-data/TileDB-SOMA/apis/python/src/tiledbsoma/util_arrow.py", line 139, in ascii_to_unicode_pyarrow_readback
    [element.as_py().decode("utf-8") for element in old_field]
  File "/Users/johnkerl/git/single-cell-data/TileDB-SOMA/apis/python/src/tiledbsoma/util_arrow.py", line 139, in <listcomp>
    [element.as_py().decode("utf-8") for element in old_field]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```
at repro-script line 77:
```
table = sdf.read_all(value_filter="foo == 40 or foo == 20")
```
even though
```
table = sdf.read_all(ids=slice(1, 2))
```
has already succeeded

# Behavior using ASCII strings

Idea: try to rebase atop https://github.com/single-cell-data/TileDB-SOMA/pull/359 -- when I do that I get at line 82 of the same repro script:
```
table = sdf.read_all(ids=slice(1, 2))
...
assert table.num_rows == 2
```
fails since `table` is
```
foo: [[-2147483648,20,-2147483648,40,-2147483648]]
bar: [[nan,5.2,nan,7.4,nan]]
baz: [["","ball","","dog",""]]
```
which is perhaps OK.

# Conclusion

[still typing up]

**Comment by johnkerl** [comment]
@ihnorton @nguyenv repro script, `tiledb-py` only:

https://gist.github.com/johnkerl/081f9decd1d8b6d9e1d942eb6b3204de

Is it reasonable to expect the ID query for rows 1 and 3, and the value-filter query for the same rows, to produce the same output?

**Comment by bkmartinjr** [comment]
@johnkerl - is there any update on this?  I would like to see this land relatively soon, as I believe it is going to be a breaking API change.

My understanding is that your gist is producing the correct output, as any query of a dense array _must_ produce a result of the same shape as the coordinates.  In the case of a dense array, the QueryCondition will not change the result shape, just its contents (filtered results are replaced with the `fill` value).  This is completely different from sparse arrays, where the result shape changes as well.

probably worth confirming, but I asked @ihnorton the same question last month, and I believe this was the answer.

**Comment by bkmartinjr** [comment]
ps. I do think that there are use cases like yours, where it would be really nice to have the option of dropping filtered values, rather than filling.

**Comment by johnkerl** [comment]
current efforts are on #466

**Comment by johnkerl** [comment]
All PRs are merged! :)
