### ISSUE TITLE
Ingestor lacks support for AWS regions outside us-east

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#391]
If I try to write to a bucket in another region, it fails to look at the default region or allow a CLI override.  Ideally it would utilize the standard AWS_ env variables.

```
$ tools/ingestor anndata/pbmc-small.h5ad s3://bruce-uswest-tmp/tmp/pbmc-small-2022-10-10-n
Traceback (most recent call last):
  File "/home/bruce/projects/TileDB-SOMA/apis/python/tools/ingestor", line 264, in <module>
    main()
  File "/home/bruce/projects/TileDB-SOMA/apis/python/tools/ingestor", line 167, in main
    ingest_one(
  File "/home/bruce/projects/TileDB-SOMA/apis/python/tools/ingestor", line 242, in ingest_one
    tiledbsoma.io.from_h5ad(exp, input_path, "mRNA")
  File "/home/bruce/projects/TileDB-SOMA/apis/python/src/tiledbsoma/io.py", line 42, in from_h5ad
    _from_h5ad_common(experiment, input_path, measurement_name, from_anndata, ctx=ctx)
  File "/home/bruce/projects/TileDB-SOMA/apis/python/src/tiledbsoma/io.py", line 74, in _from_h5ad_common
    handler_func(experiment, anndata, measurement_name, ctx)
  File "/home/bruce/projects/TileDB-SOMA/apis/python/src/tiledbsoma/io.py", line 121, in from_anndata
    experiment.create()
  File "/home/bruce/projects/TileDB-SOMA/apis/python/src/tiledbsoma/soma_experiment.py", line 56, in create
    super().create()
  File "/home/bruce/projects/TileDB-SOMA/apis/python/src/tiledbsoma/soma_collection.py", line 106, in create
    tiledb.group_create(uri=self._uri, ctx=self._ctx)
  File "/home/bruce/projects/TileDB-SOMA/venv/lib/python3.10/site-packages/tiledb/group.py", line 270, in create
    lt.Group._create(cctx, uri)
tiledb.cc.TileDBError: [TileDB::S3] Error: Error while listing with prefix 's3://bruce-uswest-tmp/tmp/pbmc-small-2022-10-10-n/__group/' and delimiter '/'
Exception:  PermanentRedirect
Error message:  Unable to parse ExceptionName: PermanentRedirect Message: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
```

**Comment by johnkerl** [comment]
@bkmartinjr this may be a documentation PR ... normally I use

```
export AWS_ACCESS_KEY_ID="*****"
export AWS_SECRET_ACCESS_KEY="*****"
export AWS_DEFAULT_REGION="xxx"
```

in my environment

but also we can add a mod within the ingestor to take a region from argv & use

```
cfg = tiledb.Config()
cfg['vfs.s3.region'] = whatever_they_asked_for
ctx = tiledb.Ctx(cfg)
...
exp = tiledbsoma.SOMAExperiment(exp_uri, ctx=ctx)
```

**Comment by bkmartinjr** [comment]
those environment variables did not work for me, when the bucket was not in us-east-1 - ie, they seem to be ignored. Not sure why.  user error?

I think we need:
* app can override as you describe with a tiledb.Ctx
* and if not specified, the environment variables are used as a backup defualt

**Comment by johnkerl** [comment]
TileDB-internal tracking number for reference: 23827
