### ISSUE TITLE
Python tiledbsoma: error when requesting index of type `bytes`

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SOMA#419]
Attempting to create a SOMAIndexedDataFrame with an index column of type python `bytes` fails.  Given that TileDB supports this underlying type as an index ([reference](https://docs.tiledb.com/main/how-to/arrays/creating-arrays/creating-dimensions)), this should work and appears to be a bug in the SOMA type handling.

See #420 for an example unit test (currently marked xfail).

Test case:
```

import pandas as pd
import pyarrow as pa
import tiledbsoma as soma


sdf = soma.DataFrame("test_dataframe")
df = pd.DataFrame(data = {
    'soma_joinid': [0,1,2],
    'bytes': [b'a', b'b', b'c'],
    'ints': [0, 1, 2]
})

tbl = pa.Table.from_pandas(df)
sdf.create(tbl.schema, index_column_names=['bytes'])
sdf.write(tbl)
```

Result:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [28], line 14
      7 df = pd.DataFrame(data = {
      8     'soma_joinid': [0,1,2],
      9     'bytes': [b'a', b'b', b'c'],
     10     'ints': [0, 1, 2]
     11 })
     13 tbl = pa.Table.from_pandas(df)
---> 14 sdf.create(tbl.schema, index_column_names=['bytes'])
     15 sdf.write(tbl)

File ~/projects/TileDB-SOMA/apis/python/src/tiledbsoma/soma_indexed_dataframe.py:56, in SOMAIndexedDataFrame.create(self, schema, index_column_names)
     50 """
     51 :param schema: Arrow Schema defining the per-column schema. This schema must define all columns, including columns to be named as index columns. If the schema includes types unsupported by the SOMA implementation, an error will be raised.
     52 
     53 :param index_column_names: A list of column names to use as user-defined index columns (e.g., ``['cell_type', 'tissue_type']``). All named columns must exist in the schema, and at least one index column name is required.
     54 """
     55 schema = _validate_schema(schema, index_column_names)
---> 56 self._create_empty(schema, index_column_names)
     57 self._is_indexed = True
     58 self._index_column_names = tuple(index_column_names)

File ~/projects/TileDB-SOMA/apis/python/src/tiledbsoma/soma_indexed_dataframe.py:90, in SOMAIndexedDataFrame._create_empty(self, schema, index_column_names)
     88         hi = np.finfo(dtype).max
     89     else:
---> 90         raise TypeError(f"Unsupported dtype {dtype}")
     91 dim = tiledb.Dim(
     92     name=index_column_name,
     93     domain=(lo, hi),
   (...)
     96     filters=[tiledb.ZstdFilter(level=level)],
     97 )
     98 dims.append(dim)

TypeError: Unsupported dtype bytes
```

Note 2013-02-02: updated repro:

```
$ cat 419b.py
#!/usr/bin/env python

import pandas as pd
import pyarrow as pa
import tiledbsoma as soma


df = pd.DataFrame(data = {
    'soma_joinid': [0,1,2],
    'bytes': [b'a', b'b', b'c'],
    'ints': [0, 1, 2]
})

tbl = pa.Table.from_pandas(df)

sdf = soma.DataFrame.create("test_dataframe", schema=tbl.schema, index_column_names=['bytes'])
sdf.write(tbl)
```

Output:

```
$ 419b.py
Traceback (most recent call last):
  File "/Users/johnkerl/git/single-cell-data/TileDB-SOMA/apis/python/./419b.py", line 16, in <module>
    sdf = soma.DataFrame.create("test_dataframe", schema=tbl.schema, index_column_names=['bytes'])
  File "/Users/johnkerl/git/single-cell-data/TileDB-SOMA/apis/python/src/tiledbsoma/dataframe.py", line 54, in create
    schema = _canonicalize_schema(schema, index_column_names)
  File "/Users/johnkerl/git/single-cell-data/TileDB-SOMA/apis/python/src/tiledbsoma/dataframe.py", line 318, in _canonicalize_schema
    raise TypeError("Unsupported index type - pending fix #418 and #419")
TypeError: Unsupported index type - pending fix #418 and #419
```

**Comment by johnkerl** [comment]
Not dup of #418 -- string indices will be supportable via tiledb-py on a nearer timescale than byte-array indices

**Comment by johnkerl** [comment]
> Dup of https://github.com/single-cell-data/TileDB-SOMA/issues/418 -- we need to support indices of type ascii or bytes

This was incorrect -- string dims are doable near-term; byte-dims are longer-term
