### ISSUE TITLE
[c++/python] Version conflict with pyarrow

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#713]
The following code errors out in a JupyterHub notebook environment but not in my sandbox. The difference is the `pyarrow` version.

Code:

```
#!/usr/bin/env python

import tiledbsoma as soma, tiledbsoma.io

import scanpy as sc
import anndata as ad
import shutil, os

uri = "repro"
if os.path.exists(uri):
    shutil.rmtree(uri)

pbmc3k = sc.datasets.pbmc3k()

tiledbsoma.logging.info()
exp = soma.Experiment(uri)
soma.io.from_anndata(exp, anndata = pbmc3k,measurement_name='pbmc')

print(next(exp.obs.read()))
```

Output in the notebook environment:

```
Wrote   repro/obs
Wrote   repro/ms/pbmc/var
Writing repro/ms/pbmc/X/data
Wrote   repro/ms/pbmc/X/data
Wrote   repro
Traceback (most recent call last):
  File "/home/jovyan/chad.py", line 19, in <module>
    print(next(exp.obs.read()))
  File "/opt/conda/lib/python3.9/site-packages/tiledbsoma/util_iter.py", line 22, in __next__
    arrow_table = self.sr.read_next()
  File "pyarrow/array.pxi", line 1331, in pyarrow.lib.Array._import_from_c
TypeError: an integer is required
```

Notebook environment: `pyarrow.__version__` is `6.0.2`

Sandbox environment: `pyarrow.__version__` is `9.0.0`

Workaround for the notebook: `pip install pyarrow==9.0.0`

**Comment by johnkerl** [comment]
Superseded by #714
