### ISSUE TITLE
[BUG] AttributeError: 'DataFrame' object has no attribute '_close_stack'

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SOMA#860]
**Describe the bug**

Trying to run the repro from #419. Error:

```
$ ./419.py
Traceback (most recent call last):
  File "/Users/johnkerl/git/single-cell-data/TileDB-SOMA/apis/python/./419.py", line 8, in <module>
    sdf = soma.DataFrame("test_dataframe")
  File "/Users/johnkerl/git/single-cell-data/TileDB-SOMA/apis/python/src/tiledbsoma/dataframe.py", line 76, in __init__
    super().__init__(handle, _this_is_internal_only=_this_is_internal_only)
  File "/Users/johnkerl/git/single-cell-data/TileDB-SOMA/apis/python/src/tiledbsoma/tiledb_object.py", line 39, in __init__
    raise TypeError(
TypeError: DataFrame initializers are intended for internal use only. To open an existing DataFrame, use tiledbsoma.open(...) or the DataFrame.open(...) class method. To create a new DataFrame, use the DataFrame.create class method.
Exception ignored in: <function SOMAObject.__del__ at 0x7f7c39e4f820>
Traceback (most recent call last):
  File "/Users/johnkerl/git/single-cell-data/SOMA/python-spec/src/somacore/base.py", line 91, in __del__
    self.close()
  File "/Users/johnkerl/git/single-cell-data/TileDB-SOMA/apis/python/src/tiledbsoma/tiledb_object.py", line 90, in close
    self._close_stack.close()
AttributeError: 'DataFrame' object has no attribute '_close_stack'
```

Note that this repro fails in the expected way:

```
$ cat 419b.py
#!/usr/bin/env python

import pandas as pd
import pyarrow as pa
import tiledbsoma as soma


df = pd.DataFrame(data = {
    'soma_joinid': [0,1,2],
    'bytes': [b'a', b'b', b'c'],
    'ints': [0, 1, 2]
})

tbl = pa.Table.from_pandas(df)

sdf = soma.DataFrame.create("test_dataframe", schema=tbl.schema, index_column_names=['bytes'])
sdf.write(tbl)
```

```
$ 419b.py
Traceback (most recent call last):
  File "/Users/johnkerl/git/single-cell-data/TileDB-SOMA/apis/python/./419b.py", line 16, in <module>
    sdf = soma.DataFrame.create("test_dataframe", schema=tbl.schema, index_column_names=['bytes'])
  File "/Users/johnkerl/git/single-cell-data/TileDB-SOMA/apis/python/src/tiledbsoma/dataframe.py", line 54, in create
    schema = _canonicalize_schema(schema, index_column_names)
  File "/Users/johnkerl/git/single-cell-data/TileDB-SOMA/apis/python/src/tiledbsoma/dataframe.py", line 318, in _canonicalize_schema
    raise TypeError("Unsupported index type - pending fix #418 and #419")
TypeError: Unsupported index type - pending fix #418 and #419
```

**To Reproduce**

Run the repro from #419.

**Versions (please complete the following information):**
 - TileDB-SOMA version: `HEAD`
 - Language and language version (e.g. Python 3.8, R 4.2.2): Python 3.9.0
 - OS (e.g. MacOS, Ubuntu Linux): MacOS

**Additional context**

The new `soma.DataFrame.create` is what people should be using. `sdf.create` fails in a very non-intuitive way. Let's shut down this entrypoint entirely.

**Comment by johnkerl** [comment]
@thetorpedodog FYI
